# -*- coding: utf-8 -*-
"""R76 simulation runner based on the live MA5/BB cross strategy.

Loads date-based TXT data from data/YYYYMMDD (typically generated by
r001_data_collect_symbols_daily.py as 20-second bars), then normalizes bars to the same
3-minute strategy cadence used in r006_trade_live_execute.py.

Run examples:
- python xgraph/auto_trading/r007_trade_simulate_by_date.py --date 20260508
- python xgraph/auto_trading/r007_trade_simulate_by_date.py --date 20260508 --codes 003490 018880

Update log format (append only):
- [YYYY-MM-DD] type=feat|fix|refactor|docs owner=<name>
    summary: <one line>
    impact: <sim/live/common>
    compatibility: <backward-compatible|breaking>

Update log:
- [2026-05-25] type=fix owner=copilot
    summary: r007 allows same-day re-entry after completed sell via simulation-only override flag.
    impact: sim
    compatibility: backward-compatible
- [2026-05-10] type=docs owner=copilot
    summary: added standardized file header and expandable update-log format.
    impact: sim
    compatibility: backward-compatible
"""

from __future__ import annotations

import argparse
import collections
import csv
import json
import logging
import re
import sys
from dataclasses import dataclass
from datetime import date, datetime, time as dt_time, timedelta
from pathlib import Path
from typing import Optional

try:
    import pandas as pd
except ModuleNotFoundError as exc:
    raise SystemExit(
        "Missing dependency: pandas. "
        "On Ubuntu, run 'python3 -m pip install -r requirements.txt' from repository root."
    ) from exc

from r003_define_config import (
    ADX_MIN_TREND,
    ADX_PERIOD,
    ADX_STRONG_TREND,
    AFTERNOON_NXT_END,
    AFTERNOON_NXT_FORCE_EXIT,
    AFTERNOON_NXT_NEW_ENTRY_CUTOFF,
    AFTERNOON_NXT_START,
    ALLOW_REBUY_SAME_CODE,
    AUX_SELL_MIN_PNL_SCORE2,
    AUX_SELL_MIN_PNL_SCORE3,
    AUX_SELL_MIN_PNL_SCORE4,
    BB_PERIOD,
    BB_SQUEEZE_MIN_WIDTH_PCT,
    BB_STD_MULTIPLIER,
    BB_UPPER_PROXIMITY_MAX,
    BOX_RANGE_HOLD_LOOKBACK_BARS,
    BOX_RANGE_HOLD_MAX_BB_WIDTH_PCT,
    BOX_RANGE_HOLD_MAX_RANGE_PCT,
    DATA_DIR_NAME,
    DEFINE_TODAY_CODE_PATH,
    EARLY_NEAR_CROSS_ALLOWED_END,
    EARLY_NEAR_CROSS_ALLOWED_START,
    EARLY_NEAR_CROSS_ALLOW_NXT,
    EARLY_NEAR_CROSS_MIN_TURNOVER_KRW,
    EARLY_NEAR_CROSS_MIN_VOL_MA,
    EARLY_NEAR_CROSS_MIN_VOLUME,
    ENABLE_BOX_RANGE_HOLD_TECH_SELL,
    ENABLE_EARLY_NEAR_CROSS_ENTRY,
    ENABLE_NEAR_CROSS_ARM,
    ENABLE_PRICE_LEAD_BB_BREAKOUT,
    ENABLE_STRONG_TREND_OVERBOUGHT_BYPASS,
    ENABLE_NXT_SESSION,
    ENABLE_STRICT_MA5_BB_GOLDEN_CROSS as REQUIRE_STRICT_BUY_GOLDEN_CROSS,
    ENABLE_TP_EXTENSION_TRAILING,
    LIVE_PRICE_BB_BUFFER_PCT as SIM_LIVE_PRICE_BB_BUFFER_PCT,
    LIVE_PRICE_CROSS_CONFIRM_POLLS,
    LIVE_PRICE_CROSS_CONFIRM_SECONDS,
    LIVE_PRICE_DOWN_CROSS_CONFIRM_POLLS,
    LIVE_PRICE_DOWN_CROSS_CONFIRM_SECONDS,
    MA5_BB_DOWN_CROSS_CONFIRM_MIN_SCORE,
    MA5_BB_DOWN_CROSS_IMMEDIATE_PNL,
    MA5_BB_DOWN_CROSS_IMMEDIATE_SCORE,
    MA5_BB_DOWN_CROSS_MIN_PNL,
    MA_PERIOD,
    MACD_FAST,
    MACD_SIGNAL_PERIOD,
    MACD_SLOW,
    MAX_ORDER_AMOUNT_KRW,
    MIN_BARS_REQUIRED,
    MORNING_NXT_END,
    MORNING_NXT_START,
    NEAR_CROSS_ARM_EXPIRE_BARS,
    NEAR_CROSS_ARM_GAP_MAX,
    NEAR_CROSS_ARM_MA_RISE_MIN,
    NEAR_CROSS_EARLY_GAP_MAX,
    NEAR_CROSS_EARLY_MA_RISE_MIN,
    OBV_BREAKOUT_LOOKBACK_BARS,
    OBV_MA_PERIOD,
    POLL_INTERVAL_SECONDS,
    PRICE_LEAD_BREAKOUT_ALLOW_OVERBOUGHT,
    PRICE_LEAD_BREAKOUT_MIN_ADX,
    PRICE_LEAD_BREAKOUT_MIN_SCORE,
    REGULAR_END,
    REGULAR_FORCE_EXIT,
    REGULAR_NEW_ENTRY_CUTOFF,
    REGULAR_START,
    RSI_BUY_MAX,
    RSI_BUY_MIN,
    RSI_PERIOD,
    RSI_SIGNAL_PERIOD,
    STARTUP_WARMUP_SECONDS,
    BREAKEVEN_FAIL_ARM_PNL,
    BREAKEVEN_FAIL_CONFIRM_SECONDS,
    BREAKEVEN_FAIL_GIVEBACK_PCT,
    NO_TREND_EXIT_ARM_SECONDS,
    NO_TREND_EXIT_CONFIRM_SECONDS,
    NO_TREND_EXIT_MAX_PEAK_PNL,
    NO_TREND_EXIT_MIN_PNL,
    POST_BUY_BB_DROP_ARMED_SECONDS,
    POST_BUY_DROP_CONFIRM_SECONDS,
    POST_BUY_BB_DROP_PCT,
    POST_BUY_BB_DROP_POLLS,
    STOP_LOSS_EARLY_PERCENT,
    STOP_LOSS_MIN_HOLD_SECONDS,
    STOP_LOSS_PERCENT,
    STOCH_BUY_MAX,
    STOCH_BUY_MIN,
    STOCH_D_PERIOD,
    STOCH_K_PERIOD,
    STOCH_OVERBOUGHT,
    STRONG_TREND_OVERBOUGHT_MIN_ADX,
    STRONG_TREND_OVERBOUGHT_MIN_SCORE,
    STRONG_TREND_OVERBOUGHT_MIN_VOL_RATIO,
    TAKE_PROFIT_PERCENT,
    TP_EXTENSION_TRAIL_FROM_PEAK,
    TRADE_COOLDOWN_MINUTES,
    TRAILING_STOP_FROM_PEAK,
    VOLUME_MA_PERIOD,
    VOLUME_RATIO_CLOSE,
    VOLUME_RATIO_FLOOR,
    VOLUME_RATIO_MIDDAY,
    VOLUME_RATIO_NXT,
    VOLUME_RATIO_OPEN,
    VOLUME_RATIO_STRONG_RELAX,
    WILLIAMS_BUY_FLOOR,
    WILLIAMS_D_PERIOD,
    WILLIAMS_OVERBOUGHT_CEIL,
    WILLIAMS_R_PERIOD,
)
from r005_strategy_core_shared import (
    R76StrategyConfig,
    check_buy_condition as shared_check_buy_condition,
    check_sell_condition as shared_check_sell_condition,
    update_timed_condition_state,
    update_live_price_cross_state as shared_update_live_price_cross_state,
)

SCRIPT_DIR = Path(__file__).resolve().parent
TODAY_CODE_FILE = SCRIPT_DIR / DEFINE_TODAY_CODE_PATH

# ---------------------------------------------------------------------------
# Simulation-only parameters (not used by live trading)
# ---------------------------------------------------------------------------
SIM_INITIAL_CAPITAL = 5_000_000
SIM_ALLOW_REENTRY_AFTER_COMPLETED_SELL = True
PICKS_FILENAME = "picks.txt"
SIM_WARMUP_TAIL_BARS = 160
SIM_WARMUP_PRIOR_MAX_DAYS = 20
NXT_ELIGIBLE_CODES_FALLBACK = frozenset(
    {"005930", "000660", "035420", "068270", "018880", "103590", "003490"}
)

# Legacy compare mode parameter (kept for compare strategy behavior)
TECH_SELL_MIN_HOLD_SECONDS = 300

SAME_DAY_MIN_BARS = 10
SIM_CHECK_INTERVAL_SECONDS = 10

SHARED_R76_CONFIG = R76StrategyConfig(
    live_price_bb_buffer_pct=SIM_LIVE_PRICE_BB_BUFFER_PCT,
    live_price_cross_confirm_polls=LIVE_PRICE_CROSS_CONFIRM_POLLS,
    live_price_cross_confirm_seconds=LIVE_PRICE_CROSS_CONFIRM_SECONDS,
    live_price_down_cross_confirm_polls=LIVE_PRICE_DOWN_CROSS_CONFIRM_POLLS,
    live_price_down_cross_confirm_seconds=LIVE_PRICE_DOWN_CROSS_CONFIRM_SECONDS,
    require_strict_buy_golden_cross=REQUIRE_STRICT_BUY_GOLDEN_CROSS,
    stoch_overbought=STOCH_OVERBOUGHT,
    williams_overbought_ceil=WILLIAMS_OVERBOUGHT_CEIL,
    bb_upper_proximity_max=BB_UPPER_PROXIMITY_MAX,
    bb_squeeze_min_width_pct=BB_SQUEEZE_MIN_WIDTH_PCT,
    adx_min_trend=ADX_MIN_TREND,
    stop_loss_percent=STOP_LOSS_PERCENT,
    take_profit_percent=TAKE_PROFIT_PERCENT,
    enable_box_range_hold_tech_sell=ENABLE_BOX_RANGE_HOLD_TECH_SELL,
    box_range_hold_lookback_bars=BOX_RANGE_HOLD_LOOKBACK_BARS,
    box_range_hold_max_range_pct=BOX_RANGE_HOLD_MAX_RANGE_PCT,
    box_range_hold_max_bb_width_pct=BOX_RANGE_HOLD_MAX_BB_WIDTH_PCT,
    ma5_bb_down_cross_min_pnl=MA5_BB_DOWN_CROSS_MIN_PNL,
    ma5_bb_down_cross_immediate_pnl=MA5_BB_DOWN_CROSS_IMMEDIATE_PNL,
    ma5_bb_down_cross_immediate_score=MA5_BB_DOWN_CROSS_IMMEDIATE_SCORE,
    aux_sell_min_pnl_score2=AUX_SELL_MIN_PNL_SCORE2,
    aux_sell_min_pnl_score3=AUX_SELL_MIN_PNL_SCORE3,
    aux_sell_min_pnl_score4=AUX_SELL_MIN_PNL_SCORE4,
    stoch_buy_min=STOCH_BUY_MIN,
    stoch_buy_max=STOCH_BUY_MAX,
    rsi_buy_min=RSI_BUY_MIN,
    rsi_buy_max=RSI_BUY_MAX,
    williams_buy_floor=WILLIAMS_BUY_FLOOR,
    obv_breakout_lookback_bars=OBV_BREAKOUT_LOOKBACK_BARS,
    enable_price_lead_bb_breakout=ENABLE_PRICE_LEAD_BB_BREAKOUT,
    price_lead_breakout_min_score=PRICE_LEAD_BREAKOUT_MIN_SCORE,
    price_lead_breakout_min_adx=PRICE_LEAD_BREAKOUT_MIN_ADX,
    price_lead_breakout_allow_overbought=PRICE_LEAD_BREAKOUT_ALLOW_OVERBOUGHT,
    enable_strong_trend_overbought_bypass=ENABLE_STRONG_TREND_OVERBOUGHT_BYPASS,
    strong_trend_overbought_min_score=STRONG_TREND_OVERBOUGHT_MIN_SCORE,
    strong_trend_overbought_min_vol_ratio=STRONG_TREND_OVERBOUGHT_MIN_VOL_RATIO,
    strong_trend_overbought_min_adx=STRONG_TREND_OVERBOUGHT_MIN_ADX,
)

SAMPLE_CODE_MAP = {
    "001440": "대한전선",
    "450080": "에코프로머티",
    "032500": "케이엠더블유",
}

log_dir = SCRIPT_DIR / "logs"
log_dir.mkdir(exist_ok=True)
DAILY_RESULT_CSV = log_dir / "r76_daily_results.csv"
COMPARE_RESULT_DIR = log_dir / "compare"

LOG_SUMMARY_MODE = False
COMPARE_FEE_BUY_RATE = 0.00015
COMPARE_FEE_SELL_RATE = 0.00015
COMPARE_SLIPPAGE_RATE = 0.00020

logging.basicConfig(
    level=logging.INFO,
    format="[%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
    force=True,
)
logger = logging.getLogger(__name__)

LAST_SIM_STATS: dict[str, float | int | str] = {}
CURRENT_SIM_TS: pd.Timestamp | None = None
INDICATOR_COLUMNS = {
    "MA_5", "VOL_MA20", "BB_MIDDLE", "BB_STD", "BB_UPPER", "BB_LOWER",
    "RSI", "RSI_SIGNAL", "STOCH_K", "STOCH_D", "WILLIAMS_R", "WILLIAMS_D",
    "MACD", "MACD_SIGNAL", "MACD_HIST", "DI_PLUS", "DI_MINUS", "ADX",
    "VWAP", "OBV", "OBV_MA",
}


def log(msg: str) -> None:
    if CURRENT_SIM_TS is not None:
        logger.info(f"{CURRENT_SIM_TS:%Y-%m-%d %H:%M:%S} | {msg}")
    else:
        logger.info(msg)


def log_detail(msg: str) -> None:
    if not LOG_SUMMARY_MODE:
        if CURRENT_SIM_TS is not None:
            logger.info(f"{CURRENT_SIM_TS:%Y-%m-%d %H:%M:%S} | {msg}")
        else:
            logger.info(msg)



# --- 로그 버퍼 및 파일 저장용 코드 추가 ---
_RAW_LOG_BUFFER: list[str] = []
def raw(msg: str) -> None:
    print(msg)
    _RAW_LOG_BUFFER.append(str(msg))


def _load_text_lines(path: Path) -> list[str]:
    for encoding in ("utf-8-sig", "utf-8", "cp949"):
        try:
            with open(path, "r", encoding=encoding) as file_obj:
                return [line.strip() for line in file_obj if line.strip()]
        except UnicodeDecodeError:
            continue
    raise UnicodeDecodeError("define_today_code", b"", 0, 1, "Unable to decode file")


def load_code_name_map(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    result: dict[str, str] = {}
    for line in _load_text_lines(path):
        if line.startswith("#"):
            continue
        parts = [part.strip() for part in line.split(",")]
        # Backward compatible formats:
        # - code,name
        # - YYYYMMDD,code,name
        if len(parts) >= 3 and parts[0].isdigit() and len(parts[0]) == 8:
            code = parts[1].zfill(6)
            name = parts[2] if parts[2] else code
        else:
            code = parts[0].zfill(6)
            name = parts[1] if len(parts) >= 2 and parts[1] else code
        result[code] = name
    return result


def load_picks(picks_file: Path) -> dict[str, str] | None:
    if not picks_file.exists():
        return None
    return load_code_name_map(picks_file)


def resolve_picks_file(data_dir: Path, date_str: str) -> Path:
    # Preferred naming: _YYYYMMDD_picks.txt (date-scoped watchlist)
    for name in (f"_{date_str}_picks.txt", f"{date_str}_picks.txt"):
        dated_picks = data_dir / name
        if dated_picks.exists():
            return dated_picks
    return data_dir / PICKS_FILENAME


def load_symbols_name_map(symbols_file: Path) -> dict[str, str]:
    if not symbols_file.exists():
        return {}
    try:
        df = pd.read_csv(symbols_file)
    except Exception as exc:
        log(f"WARNING: failed to load symbols file {symbols_file}: {exc}")
        return {}

    if "code" not in df.columns:
        return {}

    name_series = df["name"] if "name" in df.columns else None
    result: dict[str, str] = {}
    for idx, code in enumerate(df["code"].astype(str)):
        code6 = code.strip().zfill(6)
        if not code6:
            continue
        if name_series is not None:
            name = str(name_series.iloc[idx]).strip()
            result[code6] = name if name else code6
        else:
            result[code6] = code6
    return result


def read_ohlc_csv(csv_path: Path) -> pd.DataFrame | None:
    try:
        df = pd.read_csv(csv_path)
    except Exception as exc:
        log(f"CSV load failed: {csv_path} | {exc}")
        return None

    time_col = None
    for col in ("timestamp", "datetime", "Time", "time", "date", "Date"):
        if col in df.columns:
            time_col = col
            break

    if time_col:
        df[time_col] = pd.to_datetime(df[time_col], errors="coerce")
        df = df.set_index(time_col)
    else:
        df.index = pd.to_datetime(df.iloc[:, 0], errors="coerce")
        df = df.iloc[:, 1:]

    required = {"open", "high", "low", "close", "volume"}
    if not required.issubset(set(df.columns)):
        return None

    df = df[~df.index.isna()].sort_index()
    for col in required:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    df = df.dropna(subset=["open", "high", "low", "close"])
    return df if not df.empty else None


def _extract_code_from_stem(stem: str) -> str | None:
    match = re.search(r"(\d{6})", stem)
    if not match:
        return None
    return match.group(1)


def _find_code_txt_path(day_dir: Path, code: str) -> Path | None:
    """Return best file for strategy/indicator use: prefers _1m > plain > _20s."""
    target = str(code).zfill(6)
    candidates: list[Path] = []
    for path in sorted(day_dir.glob("*.txt")):
        parsed = _extract_code_from_stem(path.stem)
        if parsed == target:
            candidates.append(path)

    if not candidates:
        return None

    def _priority(path: Path) -> tuple[int, int, str]:
        stem = path.stem.lower()
        if stem.endswith("_1m"):
            tier = 0
        elif stem.endswith("_20s"):
            tier = 2
        else:
            tier = 1
        return (tier, len(path.name), path.name)

    candidates.sort(key=_priority)
    for candidate in candidates:
        return candidate
    return None


def _find_code_txt_path_finest(day_dir: Path, code: str) -> Path | None:
    """Return finest-granularity file for live-price simulation: prefers _20s > plain > _1m."""
    target = str(code).zfill(6)
    candidates: list[Path] = []
    for path in sorted(day_dir.glob("*.txt")):
        parsed = _extract_code_from_stem(path.stem)
        if parsed == target:
            candidates.append(path)

    if not candidates:
        return None

    def _fineness(path: Path) -> tuple[int, int, str]:
        stem = path.stem.lower()
        if stem.endswith("_20s"):
            tier = 0  # finest granularity
        elif stem.endswith("_1m"):
            tier = 2  # coarsest
        else:
            tier = 1
        return (tier, len(path.name), path.name)

    candidates.sort(key=_fineness)
    return candidates[0]


def find_prior_trading_day_csv(data_root: Path, as_of: date, code: str) -> Path | None:
    cursor = as_of - timedelta(days=1)
    for _ in range(SIM_WARMUP_PRIOR_MAX_DAYS):
        day_dir = data_root / cursor.strftime("%Y%m%d")
        candidate = _find_code_txt_path(day_dir, code)
        if candidate is not None and candidate.is_file():
            return candidate
        cursor -= timedelta(days=1)
    return None


def normalize_to_strategy_bars(df: pd.DataFrame) -> pd.DataFrame:
    """Normalize raw bars to 3-minute strategy bars when source is minute-level."""
    if df.empty or len(df.index) < 2:
        return df

    diffs = df.index.to_series().diff().dropna().dt.total_seconds()
    if diffs.empty:
        return df

    median_seconds = float(diffs.median())
    if median_seconds <= 90.0:
        agg_map: dict[str, str] = {
            "open": "first",
            "high": "max",
            "low": "min",
            "close": "last",
            "volume": "sum",
        }
        indicator_cols = [col for col in INDICATOR_COLUMNS if col in df.columns]
        for col in indicator_cols:
            agg_map[col] = "last"

        out = df.resample("3min", label="right", closed="right").agg(agg_map)
        out = out.dropna(subset=["open", "high", "low", "close"])
        return out

    return df


def build_simulation_frame(data_root: Path, simulation_date_str: str, code: str) -> pd.DataFrame | None:
    day_dir = data_root / simulation_date_str
    today_path = _find_code_txt_path(day_dir, code)
    if today_path is None or not today_path.is_file():
        return None

    today = read_ohlc_csv(today_path)
    if today is None or today.empty:
        return None

    merged = today

    merged = normalize_to_strategy_bars(merged)
    if merged.empty:
        return None

    return calculate_indicators(merged)


def is_regular_session(ts: pd.Timestamp) -> bool:
    return REGULAR_START <= ts.time() <= REGULAR_END


def is_nxt_session(ts: pd.Timestamp) -> bool:
    if not ENABLE_NXT_SESSION:
        return False
    current_time = ts.time()
    return (MORNING_NXT_START <= current_time <= MORNING_NXT_END) or (AFTERNOON_NXT_START <= current_time <= AFTERNOON_NXT_END)


def is_regular_call_auction(ts: pd.Timestamp) -> bool:
    current_time = ts.time()
    return REGULAR_NEW_ENTRY_CUTOFF <= current_time < REGULAR_END


def classify_buy_session(ts: pd.Timestamp) -> str:
    if not ENABLE_NXT_SESSION:
        return "regular"
    current_time = ts.time()
    if MORNING_NXT_START <= current_time <= MORNING_NXT_END:
        return "morning_nxt"
    if AFTERNOON_NXT_START <= current_time <= AFTERNOON_NXT_END:
        return "afternoon_nxt"
    return "regular"


def can_trade_code_now(ts: pd.Timestamp, nxt_tradeable: bool) -> bool:
    current_time = ts.time()
    if REGULAR_START <= current_time <= REGULAR_END:
        return True
    if not ENABLE_NXT_SESSION:
        return False
    if MORNING_NXT_START <= current_time <= MORNING_NXT_END:
        return nxt_tradeable
    if AFTERNOON_NXT_START <= current_time <= AFTERNOON_NXT_END:
        return nxt_tradeable
    return False


def is_new_entry_allowed(ts: pd.Timestamp, nxt_tradeable: bool) -> bool:
    """NXT 가능여부에 따라 매수 허용 시간 결정.
    - 정규장(09:00-15:20): 모든 종목
    - NXT 시간(08:00-08:50, 15:30-19:59): NXT 가능 종목만
    """
    if is_regular_session(ts):
        return ts.time() < REGULAR_NEW_ENTRY_CUTOFF
    if not ENABLE_NXT_SESSION:
        return False
    if is_nxt_session(ts) and nxt_tradeable:
        return ts.time() < AFTERNOON_NXT_NEW_ENTRY_CUTOFF or ts.time() <= MORNING_NXT_END
    return False


def get_session_open_timestamp(ts: pd.Timestamp, nxt_tradeable: bool) -> pd.Timestamp | None:
    current_time = ts.time()
    day = ts.date()
    if not ENABLE_NXT_SESSION:
        if REGULAR_START <= current_time <= REGULAR_END:
            return pd.Timestamp(datetime.combine(day, REGULAR_START))
        return None
    if MORNING_NXT_START <= current_time <= MORNING_NXT_END and nxt_tradeable:
        return pd.Timestamp(datetime.combine(day, MORNING_NXT_START))
    if REGULAR_START <= current_time <= REGULAR_END:
        return pd.Timestamp(datetime.combine(day, REGULAR_START))
    if AFTERNOON_NXT_START <= current_time <= AFTERNOON_NXT_END and nxt_tradeable:
        return pd.Timestamp(datetime.combine(day, AFTERNOON_NXT_START))
    return None


def is_startup_warmup_active(ts: pd.Timestamp, nxt_tradeable: bool) -> bool:
    if STARTUP_WARMUP_SECONDS <= 0:
        return False
    session_open = get_session_open_timestamp(ts, nxt_tradeable)
    if session_open is None:
        return False
    elapsed = (ts - session_open).total_seconds()
    return 0 <= elapsed < STARTUP_WARMUP_SECONDS


def get_volume_ratio_threshold(ts: pd.Timestamp, adx_val: float) -> float:
    current_time = ts.time()

    if is_nxt_session(ts):
        ratio = VOLUME_RATIO_NXT
    elif current_time < dt_time(10, 0):
        ratio = VOLUME_RATIO_OPEN
    elif current_time < dt_time(14, 30):
        ratio = VOLUME_RATIO_MIDDAY
    else:
        ratio = VOLUME_RATIO_CLOSE

    if not pd.isna(adx_val) and adx_val >= ADX_STRONG_TREND:
        ratio = max(VOLUME_RATIO_FLOOR, ratio - VOLUME_RATIO_STRONG_RELAX)

    return ratio


def is_early_near_cross_allowed(ts: pd.Timestamp, nxt_tradeable: bool) -> bool:
    current_time = ts.time()
    if is_regular_session(ts):
        return EARLY_NEAR_CROSS_ALLOWED_START <= current_time <= EARLY_NEAR_CROSS_ALLOWED_END
    if EARLY_NEAR_CROSS_ALLOW_NXT and is_nxt_session(ts) and nxt_tradeable:
        return True
    return False


def calculate_indicators(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    for column in ("open", "high", "low", "close", "volume"):
        out[column] = pd.to_numeric(out[column], errors="coerce").astype("float64")

    # 이동평균 & 볼린저밴드
    out["MA_5"] = out["close"].rolling(window=MA_PERIOD, min_periods=1).mean()
    out["VOL_MA20"] = out["volume"].rolling(window=VOLUME_MA_PERIOD, min_periods=1).mean()
    out["BB_MIDDLE"] = out["close"].rolling(window=BB_PERIOD, min_periods=1).mean()
    out["BB_STD"] = out["close"].rolling(window=BB_PERIOD, min_periods=1).std()
    out["BB_UPPER"] = out["BB_MIDDLE"] + out["BB_STD"] * BB_STD_MULTIPLIER
    out["BB_LOWER"] = out["BB_MIDDLE"] - out["BB_STD"] * BB_STD_MULTIPLIER

    # RSI - Wilder's smoothing (align with real trading script)
    delta = out["close"].diff()
    gain = delta.clip(lower=0).ewm(alpha=1.0 / RSI_PERIOD, min_periods=1, adjust=False).mean()
    loss = (-delta.clip(upper=0)).ewm(alpha=1.0 / RSI_PERIOD, min_periods=1, adjust=False).mean()
    rs = gain / loss.replace(0, float("nan"))
    out["RSI"] = 100 - (100 / (1 + rs))
    out.loc[loss == 0, "RSI"] = 100.0
    out["RSI_SIGNAL"] = out["RSI"].rolling(window=RSI_SIGNAL_PERIOD, min_periods=1).mean()

    # Stochastic Fast K(10)/D(5)
    low_n = out["low"].rolling(window=STOCH_K_PERIOD, min_periods=1).min()
    high_n = out["high"].rolling(window=STOCH_K_PERIOD, min_periods=1).max()
    denom = (high_n - low_n).replace(0, float("nan"))
    out["STOCH_K"] = 100.0 * (out["close"] - low_n) / denom
    out["STOCH_D"] = out["STOCH_K"].rolling(window=STOCH_D_PERIOD, min_periods=1).mean()

    # Williams %R(10) & %D(9)
    high_w = out["high"].rolling(window=WILLIAMS_R_PERIOD, min_periods=1).max()
    low_w = out["low"].rolling(window=WILLIAMS_R_PERIOD, min_periods=1).min()
    wr_denom = (high_w - low_w).replace(0, float("nan"))
    out["WILLIAMS_R"] = -100.0 * (high_w - out["close"]) / wr_denom
    out["WILLIAMS_D"] = out["WILLIAMS_R"].rolling(window=WILLIAMS_D_PERIOD, min_periods=1).mean()

    ema_fast = out["close"].ewm(span=MACD_FAST, adjust=False).mean()
    ema_slow = out["close"].ewm(span=MACD_SLOW, adjust=False).mean()
    out["MACD"] = ema_fast - ema_slow
    out["MACD_SIGNAL"] = out["MACD"].ewm(span=MACD_SIGNAL_PERIOD, adjust=False).mean()
    out["MACD_HIST"] = out["MACD"] - out["MACD_SIGNAL"]

    tr = pd.concat([
        out["high"] - out["low"],
        (out["high"] - out["close"].shift(1)).abs(),
        (out["low"] - out["close"].shift(1)).abs(),
    ], axis=1).max(axis=1)
    high_diff = out["high"] - out["high"].shift(1)
    low_diff = out["low"].shift(1) - out["low"]
    plus_dm = high_diff.where((high_diff > low_diff) & (high_diff > 0), 0.0)
    minus_dm = low_diff.where((low_diff > high_diff) & (low_diff > 0), 0.0)
    ema_tr = tr.ewm(alpha=1.0 / ADX_PERIOD, min_periods=1, adjust=False).mean()
    ema_plus = plus_dm.ewm(alpha=1.0 / ADX_PERIOD, min_periods=1, adjust=False).mean()
    ema_minus = minus_dm.ewm(alpha=1.0 / ADX_PERIOD, min_periods=1, adjust=False).mean()
    out["DI_PLUS"] = 100.0 * ema_plus / ema_tr.replace(0, float("nan"))
    out["DI_MINUS"] = 100.0 * ema_minus / ema_tr.replace(0, float("nan"))
    di_sum = (out["DI_PLUS"] + out["DI_MINUS"]).replace(0, float("nan"))
    dx = 100.0 * (out["DI_PLUS"] - out["DI_MINUS"]).abs() / di_sum
    out["ADX"] = dx.ewm(alpha=1.0 / ADX_PERIOD, min_periods=1, adjust=False).mean()

    # VWAP / OBV (r73 매수 스코어 반영)
    cum_vol = out["volume"].cumsum()
    out["VWAP"] = (out["close"] * out["volume"]).cumsum() / cum_vol.replace(0, float("nan"))
    close_diff = out["close"].diff()
    obv_vol = out["volume"] * close_diff.gt(0).astype(float) - out["volume"] * close_diff.lt(0).astype(float)
    out["OBV"] = obv_vol.cumsum()
    out["OBV_MA"] = out["OBV"].rolling(window=OBV_MA_PERIOD, min_periods=1).mean()

    return out


def _num(candle: pd.Series, key: str) -> float:
    value = candle.get(key)
    return float(value) if value is not None and not pd.isna(value) else float("nan")


def _buy_support_score(cur: pd.Series, prev: pd.Series, frame: pd.DataFrame | None = None) -> int:
    """매수 보조지표(0~6)."""
    score = 0

    # Stoch: K > D (3분봉 민감성 감소)
    k_c = _num(cur, "STOCH_K"); d_c = _num(cur, "STOCH_D")
    k_p = _num(prev, "STOCH_K"); d_p = _num(prev, "STOCH_D")
    if not any(pd.isna(v) for v in (k_c, d_c, k_p, d_p)):
        if k_c > d_c:
            score += 1

    # RSI: 50 이상 70 미만 + 상승 확인
    rsi_c = _num(cur, "RSI")
    rsi_p = _num(prev, "RSI")
    if not any(pd.isna(v) for v in (rsi_c, rsi_p)):
        if RSI_BUY_MIN <= rsi_c < RSI_BUY_MAX and rsi_c > rsi_p:
            score += 1

    # Williams %R(10): 상승 중이거나 과매수 복귀
    wr_c = _num(cur, "WILLIAMS_R"); wr_p = _num(prev, "WILLIAMS_R")
    if not pd.isna(wr_c) and not pd.isna(wr_p):
        if wr_c > wr_p and wr_c >= WILLIAMS_BUY_FLOOR:
            score += 1

    # MACD: MACD > Signal + 히스토그램이 양수 또는 수축
    macd_c = _num(cur, "MACD")
    msig_c = _num(cur, "MACD_SIGNAL")
    hist_c = _num(cur, "MACD_HIST")
    hist_p = _num(prev, "MACD_HIST")
    if not any(pd.isna(v) for v in (macd_c, msig_c, hist_c)):
        hist_accel = (hist_c > 0) or (not pd.isna(hist_p) and hist_c < 0 and hist_c > hist_p)
        if macd_c > msig_c and hist_accel:
            score += 1

    # VWAP
    vwap = _num(cur, "VWAP")
    close_v = _num(cur, "close")
    if not pd.isna(vwap) and not pd.isna(close_v) and close_v > vwap:
        score += 1

    # OBV: 최근 5봉 고점 돌파 또는 OBV 상승
    obv_c = _num(cur, "OBV")
    obv_ma_c = _num(cur, "OBV_MA")
    obv_p = _num(prev, "OBV")
    obv_breakout = False
    if frame is not None and "OBV" in frame.columns and len(frame) >= OBV_BREAKOUT_LOOKBACK_BARS + 1:
        obv_series = pd.to_numeric(frame["OBV"], errors="coerce")
        recent_obv_high = obv_series.iloc[-(OBV_BREAKOUT_LOOKBACK_BARS + 1):-1].max()
        if not pd.isna(obv_c) and not pd.isna(recent_obv_high):
            obv_breakout = obv_c > float(recent_obv_high)
    obv_uptrend = not any(pd.isna(v) for v in (obv_c, obv_ma_c, obv_p)) and (obv_c > obv_ma_c and obv_c > obv_p)
    if obv_breakout or obv_uptrend:
        score += 1

    return score


def _sell_support_score(cur: pd.Series, prev: pd.Series) -> int:
    """매도 보조지표(0~5)."""
    score = 0

    k_c = _num(cur, "STOCH_K"); d_c = _num(cur, "STOCH_D")
    k_p = _num(prev, "STOCH_K"); d_p = _num(prev, "STOCH_D")
    if not any(pd.isna(v) for v in (k_c, d_c, k_p, d_p)):
        if k_c < d_c:
            score += 1

    rsi_c = _num(cur, "RSI"); sig_c = _num(cur, "RSI_SIGNAL")
    rsi_p = _num(prev, "RSI"); sig_p = _num(prev, "RSI_SIGNAL")
    if not any(pd.isna(v) for v in (rsi_c, sig_c, rsi_p, sig_p)):
        if rsi_p >= sig_p and rsi_c < sig_c:
            score += 1

    wr_c = _num(cur, "WILLIAMS_R"); wd_c = _num(cur, "WILLIAMS_D")
    wr_p = _num(prev, "WILLIAMS_R"); wd_p = _num(prev, "WILLIAMS_D")
    if not any(pd.isna(v) for v in (wr_c, wd_c, wr_p, wd_p)):
        if wr_p >= wd_p and wr_c < wd_c:
            score += 1

    macd_c = _num(cur, "MACD")
    msig_c = _num(cur, "MACD_SIGNAL")
    macd_p = _num(prev, "MACD")
    msig_p = _num(prev, "MACD_SIGNAL")
    if not any(pd.isna(v) for v in (macd_c, msig_c, macd_p, msig_p)):
        if macd_p >= msig_p and macd_c < msig_c:
            score += 1

    obv_c = _num(cur, "OBV")
    obv_ma_c = _num(cur, "OBV_MA")
    obv_p = _num(prev, "OBV")
    if not any(pd.isna(v) for v in (obv_c, obv_ma_c, obv_p)):
        if obv_c < obv_ma_c and obv_c < obv_p:
            score += 1

    return score


def _near_cross_momentum_flags(cur: pd.Series, prev: pd.Series) -> dict[str, float | bool]:
    prev_ma5 = _num(prev, "MA_5")
    cur_ma5 = _num(cur, "MA_5")
    prev_bb = _num(prev, "BB_MIDDLE")
    cur_bb = _num(cur, "BB_MIDDLE")

    if any(pd.isna(v) for v in (prev_ma5, cur_ma5, prev_bb, cur_bb)):
        return {"can_arm": False, "can_early": False, "gap_ratio": float("nan"), "ma_rise_ratio": float("nan")}

    gap = cur_bb - cur_ma5
    gap_ratio = gap / max(abs(cur_bb), 1.0)
    ma_rise_ratio = (cur_ma5 - prev_ma5) / max(abs(prev_ma5), 1.0)

    below_or_equal = cur_ma5 <= cur_bb
    arm_shape_ok = (prev_ma5 <= prev_bb) and below_or_equal

    can_arm = arm_shape_ok and (gap_ratio >= 0) and (gap_ratio <= NEAR_CROSS_ARM_GAP_MAX) and (ma_rise_ratio >= NEAR_CROSS_ARM_MA_RISE_MIN)
    can_early = arm_shape_ok and (gap_ratio >= 0) and (gap_ratio <= NEAR_CROSS_EARLY_GAP_MAX) and (ma_rise_ratio >= NEAR_CROSS_EARLY_MA_RISE_MIN)

    return {
        "can_arm": can_arm,
        "can_early": can_early,
        "gap_ratio": float(gap_ratio),
        "ma_rise_ratio": float(ma_rise_ratio),
    }


def _passes_early_near_cross_liquidity(cur: pd.Series) -> tuple[bool, str]:
    vol = _num(cur, "volume")
    vol_ma = _num(cur, "VOL_MA20")
    close_v = _num(cur, "close")
    if any(pd.isna(v) for v in (vol, vol_ma, close_v)):
        return False, "LIQUIDITY_DATA_NAN"

    turnover = close_v * vol
    if vol < EARLY_NEAR_CROSS_MIN_VOLUME:
        return False, f"LOW_ABS_VOLUME_{vol:.0f}_LT_{EARLY_NEAR_CROSS_MIN_VOLUME}"
    if vol_ma < EARLY_NEAR_CROSS_MIN_VOL_MA:
        return False, f"LOW_VOL_MA_{vol_ma:.0f}_LT_{EARLY_NEAR_CROSS_MIN_VOL_MA}"
    if turnover < EARLY_NEAR_CROSS_MIN_TURNOVER_KRW:
        return False, f"LOW_TURNOVER_{turnover:,.0f}_LT_{EARLY_NEAR_CROSS_MIN_TURNOVER_KRW:,}"
    return True, "OK"


def _is_box_range_hold_zone(frame: pd.DataFrame) -> tuple[bool, str]:
    if len(frame) < BOX_RANGE_HOLD_LOOKBACK_BARS:
        return False, "INSUFFICIENT_BOX_BARS"

    recent = frame.tail(BOX_RANGE_HOLD_LOOKBACK_BARS)
    high_v = pd.to_numeric(recent["high"], errors="coerce").max()
    low_v = pd.to_numeric(recent["low"], errors="coerce").min()
    close_v = _num(recent.iloc[-1], "close")
    bb_up = _num(recent.iloc[-1], "BB_UPPER")
    bb_low = _num(recent.iloc[-1], "BB_LOWER")

    if any(pd.isna(v) for v in (high_v, low_v, close_v, bb_up, bb_low)) or close_v <= 0:
        return False, "BOX_DATA_NAN"

    range_pct = (float(high_v) - float(low_v)) / float(close_v)
    bb_width_pct = (float(bb_up) - float(bb_low)) / float(close_v)
    is_box = range_pct <= BOX_RANGE_HOLD_MAX_RANGE_PCT and bb_width_pct <= BOX_RANGE_HOLD_MAX_BB_WIDTH_PCT

    return is_box, f"RANGE_{range_pct*100:.2f}%_BBW_{bb_width_pct*100:.2f}%"


def check_buy_condition(frame: pd.DataFrame, now: pd.Timestamp) -> tuple[bool, str]:
    """MA5가 BB 중심선을 상향 돌파하는 시점의 진입 조건."""
    if len(frame) < 3:
        return False, "INSUFFICIENT_BARS"

    cur = frame.iloc[-1]
    prev = frame.iloc[-2]

    prev_ma5 = _num(prev, "MA_5"); cur_ma5 = _num(cur, "MA_5")
    prev_bb = _num(prev, "BB_MIDDLE"); cur_bb = _num(cur, "BB_MIDDLE")

    if any(pd.isna(v) for v in (prev_ma5, cur_ma5, prev_bb, cur_bb)):
        return False, "MISSING_INDICATOR"

    # MA5가 BB 중심선을 상향 돌파
    ma5_cross = prev_ma5 <= prev_bb and cur_ma5 > cur_bb
    if not ma5_cross:
        return False, "NO_MA5_BB_CROSS_UP"

    # MA5/BB 중심선 방향 확인
    if cur_bb < prev_bb:
        return False, "BB_MID_FALLING"
    if cur_ma5 < prev_ma5:
        return False, "MA5_FALLING"

    # 도지봉
    if float(cur["close"]) <= float(cur["open"]):
        return False, "NOT_BULLISH"

    stoch_k = _num(cur, "STOCH_K")
    if not pd.isna(stoch_k) and stoch_k >= STOCH_OVERBOUGHT:
        return False, f"OVERBOUGHT_STOCH_{stoch_k:.1f}"

    wr_val = _num(cur, "WILLIAMS_R")
    if not pd.isna(wr_val) and wr_val >= WILLIAMS_OVERBOUGHT_CEIL:
        return False, f"OVERBOUGHT_WR_{wr_val:.1f}"

    bb_up = _num(cur, "BB_UPPER")
    bb_low = _num(cur, "BB_LOWER")
    close_val = _num(cur, "close")
    if not any(pd.isna(v) for v in (bb_up, bb_low, close_val)) and bb_up > bb_low:
        bb_pos = (close_val - bb_low) / (bb_up - bb_low)
        if bb_pos >= BB_UPPER_PROXIMITY_MAX:
            return False, f"NEAR_BB_UPPER_{bb_pos:.2f}"

    adx_val = _num(cur, "ADX")

    # 거래량 필터
    vol = _num(cur, "volume")
    vol_ma = _num(cur, "VOL_MA20")
    if not any(pd.isna(v) for v in (vol, vol_ma)) and vol_ma > 0:
        ratio = get_volume_ratio_threshold(now, adx_val)
        if vol < (vol_ma * ratio):
            return False, f"LOW_VOLUME_{(vol / vol_ma):.2f}_LT_{ratio:.2f}"

    if not pd.isna(adx_val) and adx_val < ADX_MIN_TREND:
        return False, f"WEAK_TREND_ADX_{adx_val:.1f}"

    # 매도 보조지표 3
    support_score = _buy_support_score(cur, prev, frame=frame)
    # --- 추가 필수 조건 ---
    vwap = _num(cur, "VWAP")
    close_v = _num(cur, "close")
    if pd.isna(vwap) or pd.isna(close_v) or not (close_v > vwap):
        return False, "NO_VWAP_BREAK"

    # 거래량 > 평균 거래량 1.5배
    if not any(pd.isna(v) for v in (vol, vol_ma)) and vol_ma > 0:
        if vol < (vol_ma * 1.5):
            return False, f"LOW_VOLUME_1.5X_{(vol / vol_ma):.2f}"

    # RSI > 55
    rsi_c = _num(cur, "RSI")
    if pd.isna(rsi_c) or rsi_c <= 55:
        return False, f"RSI_TOO_LOW_{rsi_c:.2f}"

    # MACD Histogram 증가
    hist_c = _num(cur, "MACD_HIST")
    hist_p = _num(prev, "MACD_HIST")
    if pd.isna(hist_c) or pd.isna(hist_p) or not (hist_c > hist_p):
        return False, f"MACD_HIST_NOT_INCREASING_{hist_p:.2f}_TO_{hist_c:.2f}"

    # 체결강도 > 120 (값이 있으면 체크)
    exec_strength = _num(cur, "EXECUTION_STRENGTH") if "EXECUTION_STRENGTH" in cur else float('nan')
    if not pd.isna(exec_strength) and exec_strength <= 120:
        return False, f"EXEC_STRENGTH_TOO_LOW_{exec_strength:.2f}"

    if support_score < 3:
        return False, f"LOW_SCORE_{support_score}"

    return True, f"MA5_BB_UP_CROSS_SCORE_{support_score}"


def check_sell_condition(frame: pd.DataFrame, pnl_pct: float, held_seconds: float | None = None) -> tuple[bool, str]:
    """r76 매도 조건(MA5 데드크로스, 이익/손실/보조지표/박스구간 등)."""
    if len(frame) < 2:
        return False, "INSUFFICIENT_BARS"

    if held_seconds is not None and held_seconds < TECH_SELL_MIN_HOLD_SECONDS:
        return False, f"TECH_SELL_MIN_HOLD_{held_seconds:.0f}s_LT_{TECH_SELL_MIN_HOLD_SECONDS}s"

    if ENABLE_BOX_RANGE_HOLD_TECH_SELL and STOP_LOSS_PERCENT < pnl_pct < TAKE_PROFIT_PERCENT:
        is_box, box_info = _is_box_range_hold_zone(frame)
        if is_box:
            return False, f"BOX_RANGE_HOLD_{box_info}"

    cur = frame.iloc[-1]
    prev = frame.iloc[-2]

    prev_ma5 = _num(prev, "MA_5"); cur_ma5 = _num(cur, "MA_5")
    prev_bb = _num(prev, "BB_MIDDLE"); cur_bb = _num(cur, "BB_MIDDLE")

    # MA5 dead cross
    ma5_dead = (
        not any(pd.isna(v) for v in (prev_ma5, cur_ma5, prev_bb, cur_bb))
        and prev_ma5 >= prev_bb
        and cur_ma5 < cur_bb
    )

    if ma5_dead:
        if pnl_pct < MA5_BB_DOWN_CROSS_MIN_PNL:
            return False, (
                f"MA5_BB_DOWN_CROSS_BLOCKED_PNL_{pnl_pct*100:.2f}%"
                f"_LT_{MA5_BB_DOWN_CROSS_MIN_PNL*100:.2f}%"
            )

        score = _sell_support_score(cur, prev)
        if pnl_pct <= MA5_BB_DOWN_CROSS_IMMEDIATE_PNL or score >= MA5_BB_DOWN_CROSS_IMMEDIATE_SCORE:
            if score >= 1:
                return True, f"MA5_BB_DOWN_CROSS_CONFIRMED_{score}"
            return True, "MA5_BB_DOWN_CROSS"

        return False, f"MA5_BB_DOWN_CROSS_ARMED_{score}"

    if len(frame) >= 3:
        prev2 = frame.iloc[-3]
        prev2_ma5 = _num(prev2, "MA_5")
        prev2_bb = _num(prev2, "BB_MIDDLE")
        prev_cross = (
            not any(pd.isna(v) for v in (prev2_ma5, prev_ma5, prev2_bb, prev_bb))
            and prev2_ma5 >= prev2_bb
            and prev_ma5 < prev_bb
        )
        cur_below = not any(pd.isna(v) for v in (cur_ma5, cur_bb)) and cur_ma5 < cur_bb
        if prev_cross and cur_below:
            if pnl_pct < MA5_BB_DOWN_CROSS_MIN_PNL:
                return False, (
                    f"MA5_BB_DOWN_CROSS_NEXT_BAR_BLOCKED_PNL_{pnl_pct*100:.2f}%"
                    f"_LT_{MA5_BB_DOWN_CROSS_MIN_PNL*100:.2f}%"
                )

            score = _sell_support_score(cur, prev)
            if score >= MA5_BB_DOWN_CROSS_CONFIRM_MIN_SCORE:
                return True, f"MA5_BB_DOWN_CROSS_NEXT_BAR_{score}"
            return True, "MA5_BB_DOWN_CROSS_NEXT_BAR"

    score = _sell_support_score(cur, prev)
    min_pnl_req = None
    if score >= 4:
        min_pnl_req = AUX_SELL_MIN_PNL_SCORE4
    elif score == 3:
        min_pnl_req = AUX_SELL_MIN_PNL_SCORE3
    elif score == 2:
        min_pnl_req = AUX_SELL_MIN_PNL_SCORE2

    if min_pnl_req is not None:
        if pnl_pct >= min_pnl_req:
            return True, f"AUX_REVERSAL_SCORE_{score}"
        return False, f"AUX_BLOCKED_SCORE_{score}_PNL_{pnl_pct*100:.2f}%_LT_{min_pnl_req*100:.2f}%"

    return False, "NO_SELL_SIGNAL"


def check_buy_condition_basic(frame: pd.DataFrame) -> tuple[bool, str]:
    if len(frame) < 3:
        return False, "INSUFFICIENT_BARS"

    cur = frame.iloc[-1]
    prev = frame.iloc[-2]
    prev_ma5 = _num(prev, "MA_5")
    cur_ma5 = _num(cur, "MA_5")
    prev_bb = _num(prev, "BB_MIDDLE")
    cur_bb = _num(cur, "BB_MIDDLE")

    if any(pd.isna(v) for v in (prev_ma5, cur_ma5, prev_bb, cur_bb)):
        return False, "MISSING_INDICATOR"

    if prev_ma5 <= prev_bb and cur_ma5 > cur_bb:
        return True, "BASIC_MA5_BB_UP_CROSS"
    return False, "NO_BASIC_MA5_BB_CROSS_UP"


def check_sell_condition_basic(frame: pd.DataFrame) -> tuple[bool, str]:
    if len(frame) < 2:
        return False, "INSUFFICIENT_BARS"

    cur = frame.iloc[-1]
    prev = frame.iloc[-2]
    prev_ma5 = _num(prev, "MA_5")
    cur_ma5 = _num(cur, "MA_5")
    prev_bb = _num(prev, "BB_MIDDLE")
    cur_bb = _num(cur, "BB_MIDDLE")

    if any(pd.isna(v) for v in (prev_ma5, cur_ma5, prev_bb, cur_bb)):
        return False, "MISSING_INDICATOR"

    if prev_ma5 >= prev_bb and cur_ma5 < cur_bb:
        return True, "BASIC_MA5_BB_DOWN_CROSS"
    return False, "NO_BASIC_MA5_BB_CROSS_DOWN"


@dataclass
class PaperStats:
    trades: int = 0
    wins: int = 0
    losses: int = 0
    pnl_sum_pct: float = 0.0
    equity: float = 1.0


class PaperStrategyTracker:
    def __init__(self, name: str, mode: str):
        self.name = name
        self.mode = mode  # basic / multi
        self.positions: dict[str, dict] = {}
        self.traded_today: set[str] = set()
        self.last_bar_seen: dict[str, pd.Timestamp] = {}
        self.stats = PaperStats()
        # mode="multi" tracks per-code live-price/BB cross state (same as main Simulator)
        self.cross_state: dict[str, dict] = {}

    def _on_close(self, code: str, price: float, reason: str) -> None:
        pos = self.positions.pop(code, None)
        if pos is None:
            return
        entry = float(pos["entry_exec_price"])
        if entry <= 0:
            return
        exit_exec = float(price) * (1.0 - COMPARE_SLIPPAGE_RATE - COMPARE_FEE_SELL_RATE)
        pnl = (exit_exec / entry) - 1.0
        self.stats.trades += 1
        self.stats.pnl_sum_pct += pnl
        self.stats.equity *= max(0.0, 1.0 + pnl)
        if pnl > 0:
            self.stats.wins += 1
        else:
            self.stats.losses += 1
        log_detail(
            f"[COMPARE-{self.name}] SELL | {code} | {reason} | "
            f"raw_exit={price:,.0f} exec_exit={exit_exec:,.0f} pnl={pnl*100:.2f}%"
        )

    def on_bar(self, code: str, frame: pd.DataFrame, ts: pd.Timestamp, entry_allowed: bool, live_price: float | None = None) -> None:
        if frame is None or frame.empty:
            return

        price = float(frame.iloc[-1]["close"])
        _lp = live_price if live_price is not None else price

        # mode="multi": update cross_state on EVERY tick (not gated by bar dedup)
        # Matches main Simulator which updates sim_live_cross_state each 20s tick.
        _multi_cross_info: dict[str, object] = {"signal": None, "relation": "on", "upper_trigger": 0.0, "lower_trigger": 0.0}
        if self.mode == "multi":
            _cur_bar_for_cross = frame.iloc[-1]
            _bb_mid = _num(_cur_bar_for_cross, "BB_MIDDLE")
            if not pd.isna(_bb_mid):
                _multi_cross_info = _update_sim_cross_state(self.cross_state, code, ts, _lp, _bb_mid)

        bar_time = frame.index[-1]
        if self.last_bar_seen.get(code) == bar_time:
            return
        self.last_bar_seen[code] = bar_time

        if code in self.positions:
            if self.mode == "basic":
                sell_ok, reason = check_sell_condition_basic(frame)
            else:
                pos = self.positions[code]
                entry = float(pos["entry_price"])
                pnl_pct = (price / entry) - 1.0
                pos["highest_price"] = max(float(pos.get("highest_price", price)), price)
                highest = float(pos.get("highest_price", price))
                if pnl_pct <= STOP_LOSS_PERCENT:
                    sell_ok, reason = True, f"STOP_LOSS_{STOP_LOSS_PERCENT*100:.1f}%"
                else:
                    peak_pnl = (highest / entry) - 1.0 if entry > 0 else 0.0
                    giveback = peak_pnl - pnl_pct
                    if ENABLE_TP_EXTENSION_TRAILING and peak_pnl >= TAKE_PROFIT_PERCENT:
                        trail = TP_EXTENSION_TRAIL_FROM_PEAK
                        ts_reason = f"TP_EXTENSION_TRAIL_{TP_EXTENSION_TRAIL_FROM_PEAK*100:.1f}%"
                    else:
                        trail = TRAILING_STOP_FROM_PEAK
                        ts_reason = f"TRAILING_STOP_GIVEBACK_{TRAILING_STOP_FROM_PEAK*100:.1f}%"
                    if peak_pnl > 0 and pnl_pct > 0 and giveback >= trail:
                        sell_ok, reason = True, ts_reason
                    else:
                        held_seconds = (ts - pos["buy_time"]).total_seconds() if isinstance(pos.get("buy_time"), pd.Timestamp) else None
                        sell_ok, reason = check_sell_condition(frame, pnl_pct, held_seconds)

            if sell_ok:
                self._on_close(code, price, reason)
            return

        if not entry_allowed:
            return
        if (not ALLOW_REBUY_SAME_CODE) and (not SIM_ALLOW_REENTRY_AFTER_COMPLETED_SELL) and code in self.traded_today:
            return

        if self.mode == "basic":
            buy_ok, reason = check_buy_condition_basic(frame)
        else:
            # Use shared live-price/BB cross logic (same as r006 live trading)
            buy_ok, reason = check_buy_condition_r76_sim(frame, ts, _lp, _multi_cross_info)

        if not buy_ok:
            return

        entry_exec = float(price) * (1.0 + COMPARE_SLIPPAGE_RATE + COMPARE_FEE_BUY_RATE)
        self.positions[code] = {
            "entry_price": float(price),
            "entry_exec_price": float(entry_exec),
            "highest_price": float(price),
            "buy_time": ts,
        }
        self.traded_today.add(code)
        log_detail(
            f"[COMPARE-{self.name}] BUY  | {code} | {reason} | "
            f"raw_entry={price:,.0f} exec_entry={entry_exec:,.0f}"
        )

    def force_close_all(self, price_map: dict[str, float], reason: str) -> None:
        for code in list(self.positions.keys()):
            price = float(price_map.get(code) or self.positions[code].get("entry_price") or 0.0)
            if price > 0:
                self._on_close(code, price, reason)

    def summary_dict(self) -> dict[str, float | int]:
        trades = self.stats.trades
        win_rate = (self.stats.wins / trades * 100.0) if trades else 0.0
        avg_pnl = (self.stats.pnl_sum_pct / trades * 100.0) if trades else 0.0
        total_pnl = self.stats.pnl_sum_pct * 100.0
        return {
            "trades": trades,
            "wins": self.stats.wins,
            "losses": self.stats.losses,
            "win_rate": win_rate,
            "avg_pnl_pct": avg_pnl,
            "total_pnl_pct": total_pnl,
            "equity": self.stats.equity,
        }


def _update_sim_cross_state(
    cross_state: dict[str, dict],
    code: str,
    now: pd.Timestamp,
    live_price: float,
    bb_middle: float,
) -> dict[str, object]:
    return shared_update_live_price_cross_state(
        cross_state=cross_state,
        code=code,
        now=now,
        live_price=live_price,
        bb_middle=bb_middle,
        config=SHARED_R76_CONFIG,
    )


def check_buy_condition_r76_sim(
    frame: pd.DataFrame,
    ts: pd.Timestamp,
    live_price: float,
    cross_info: dict[str, object],
) -> tuple[bool, str]:
    return shared_check_buy_condition(
        frame=frame,
        now=ts,
        live_price=live_price,
        cross_info=cross_info,
        config=SHARED_R76_CONFIG,
        volume_ratio_threshold_fn=get_volume_ratio_threshold,
    )


def collect_buy_reject_reasons_r76_sim(
    frame: pd.DataFrame,
    ts: pd.Timestamp,
    live_price: float,
    cross_info: dict[str, object],
    primary_reason: str,
) -> list[str]:
    reasons: list[str] = []
    if primary_reason:
        reasons.append(primary_reason)

    if len(frame) < 2:
        return list(dict.fromkeys(reasons))

    cur = frame.iloc[-1]
    prev = frame.iloc[-2]
    cur_bb = _num(cur, "BB_MIDDLE")
    prev_bb = _num(prev, "BB_MIDDLE")
    cur_ma5 = _num(cur, "MA_5")
    prev_ma5 = _num(prev, "MA_5")
    if any(pd.isna(v) for v in (cur_bb, prev_bb, cur_ma5, prev_ma5)):
        if "MISSING_INDICATOR" not in reasons:
            reasons.append("MISSING_INDICATOR")
        return list(dict.fromkeys(reasons))

    score = _buy_support_score(cur, prev, frame=frame)
    live_cross_up_signal = cross_info.get("signal") == "cross_up"
    confirmed_above = cross_info.get("confirmed_relation") == "above"
    ma5_bias_ok = cur_ma5 >= cur_bb and cur_ma5 >= prev_ma5
    upper_trigger = float(cross_info.get("upper_trigger", cur_bb))
    strong_signal_fallback = (
        score >= SHARED_R76_CONFIG.strong_trend_overbought_min_score
        and live_price > cur_bb
        and cur_bb >= prev_bb
        and ma5_bias_ok
    )
    fallback_ok = (confirmed_above and ma5_bias_ok and live_price >= upper_trigger) or strong_signal_fallback
    if (not live_cross_up_signal) and (not fallback_ok):
        reasons.append("NO_LIVE_PRICE_BB_CROSS_UP")

    if SHARED_R76_CONFIG.require_strict_buy_golden_cross:
        ma5_golden_cross_now = prev_ma5 <= prev_bb and cur_ma5 > cur_bb
        if not ma5_golden_cross_now:
            reasons.append("NO_MA5_BB_GOLDEN_CROSS")

    if live_price <= cur_bb:
        reasons.append("LIVE_PRICE_NOT_ABOVE_BB_MIDDLE")
    if cur_bb < prev_bb:
        reasons.append("BB_MIDDLE_FALLING")
    if cur_ma5 < prev_ma5:
        reasons.append("MA5_FALLING")

    cur_open = _num(cur, "open")
    if not pd.isna(cur_open) and cur_open > 0 and live_price < (cur_open * 0.995):
        reasons.append("NOT_BULLISH")

    stoch_k = _num(cur, "STOCH_K")
    is_stoch_overbought = not pd.isna(stoch_k) and stoch_k >= SHARED_R76_CONFIG.stoch_overbought
    bypass_overbought = (
        SHARED_R76_CONFIG.enable_strong_trend_overbought_bypass
        and score >= SHARED_R76_CONFIG.strong_trend_overbought_min_score
    )
    if is_stoch_overbought and not bypass_overbought:
        reasons.append(f"OVERBOUGHT_STOCH_{stoch_k:.1f}")

    wr_val = _num(cur, "WILLIAMS_R")
    if not pd.isna(wr_val) and wr_val >= SHARED_R76_CONFIG.williams_overbought_ceil:
        reasons.append(f"OVERBOUGHT_WR_{wr_val:.1f}")

    bb_up = _num(cur, "BB_UPPER")
    bb_low = _num(cur, "BB_LOWER")
    if not any(pd.isna(v) for v in (bb_up, bb_low)) and bb_up > bb_low:
        bb_pos = (live_price - bb_low) / (bb_up - bb_low)
        if bb_pos >= SHARED_R76_CONFIG.bb_upper_proximity_max:
            reasons.append(f"NEAR_BB_UPPER_{bb_pos:.2f}")

    cur_close = _num(cur, "close")
    if not any(pd.isna(v) for v in (bb_up, bb_low, cur_close)) and cur_close > 0:
        bb_width_pct = (bb_up - bb_low) / cur_close
        if bb_width_pct < SHARED_R76_CONFIG.bb_squeeze_min_width_pct:
            reasons.append(
                f"BB_SQUEEZE_{bb_width_pct*100:.2f}%_LT_{SHARED_R76_CONFIG.bb_squeeze_min_width_pct*100:.2f}%"
            )

    adx_val = _num(cur, "ADX")
    vol = _num(cur, "volume")
    vol_ma = _num(cur, "VOL_MA20")
    if not any(pd.isna(v) for v in (vol, vol_ma)) and vol_ma > 0:
        ratio = get_volume_ratio_threshold(ts, adx_val)
        if vol < (vol_ma * ratio):
            reasons.append(f"LOW_VOLUME_{(vol / vol_ma):.2f}_LT_{ratio:.2f}")

    if not pd.isna(adx_val) and adx_val < SHARED_R76_CONFIG.adx_min_trend:
        reasons.append(f"WEAK_TREND_ADX_{adx_val:.1f}")

    vwap = _num(cur, "VWAP")
    close_v = _num(cur, "close")
    if pd.isna(vwap) or pd.isna(close_v) or not (close_v > vwap):
        reasons.append("NO_VWAP_BREAK")

    if not any(pd.isna(v) for v in (vol, vol_ma)) and vol_ma > 0 and vol < (vol_ma * 1.5):
        reasons.append(f"LOW_VOLUME_1.5X_{(vol / vol_ma):.2f}")

    rsi_c = _num(cur, "RSI")
    if pd.isna(rsi_c) or rsi_c <= 55:
        reasons.append(f"RSI_TOO_LOW_{rsi_c:.2f}")

    hist_c = _num(cur, "MACD_HIST")
    hist_p = _num(prev, "MACD_HIST")
    if pd.isna(hist_c) or pd.isna(hist_p) or not (hist_c > hist_p):
        reasons.append(f"MACD_HIST_NOT_INCREASING_{hist_p:.2f}_TO_{hist_c:.2f}")

    exec_strength = _num(cur, "EXECUTION_STRENGTH") if "EXECUTION_STRENGTH" in cur else float("nan")
    if not pd.isna(exec_strength) and exec_strength <= 120:
        reasons.append(f"EXEC_STRENGTH_TOO_LOW_{exec_strength:.2f}")

    if score < 2:
        reasons.append(f"LOW_SCORE_{score}")

    return list(dict.fromkeys(reasons))


def check_sell_condition_r76_sim(
    frame: pd.DataFrame,
    pnl_pct: float,
    live_price: float,
    cross_info: dict[str, object],
) -> tuple[bool, str]:
    return shared_check_sell_condition(
        frame=frame,
        pnl_pct=pnl_pct,
        live_price=live_price,
        cross_info=cross_info,
        config=SHARED_R76_CONFIG,
    )


def append_daily_result_csv(row: dict[str, object], csv_path: Path = DAILY_RESULT_CSV) -> None:
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(row.keys())
    write_header = not csv_path.exists()
    with open(csv_path, "a", newline="", encoding="utf-8") as file_obj:
        writer = csv.DictWriter(file_obj, fieldnames=fieldnames)
        if write_header:
            writer.writeheader()
        writer.writerow(row)


def append_compare_result_csv(date_str: str, strategy_name: str, row: dict[str, object], result_dir: Path = COMPARE_RESULT_DIR) -> None:
    result_dir.mkdir(parents=True, exist_ok=True)
    csv_path = result_dir / f"{date_str}_{strategy_name}.csv"
    fieldnames = list(row.keys())
    write_header = not csv_path.exists()
    with open(csv_path, "a", newline="", encoding="utf-8") as file_obj:
        writer = csv.DictWriter(file_obj, fieldnames=fieldnames)
        if write_header:
            writer.writeheader()
        writer.writerow(row)


class TradeRecord:
    def __init__(
        self,
        code: str,
        name: str,
        action: str,
        bar_time: pd.Timestamp,
        price: float,
        qty: int,
        reason: str,
        session: str,
    ):
        self.code = code
        self.name = name
        self.action = action
        self.bar_time = bar_time
        self.price = price
        self.qty = qty
        self.reason = reason
        self.session = session
        self.pnl_pct: float | None = None
        self.pnl_krw: float | None = None

    def __repr__(self) -> str:
        pnl_str = f" | pnl={self.pnl_pct:.2f}%" if self.pnl_pct is not None else ""
        return (
            f"{self.bar_time:%H:%M} | {self.action:4s} | {self.code}({self.name}) | "
            f"qty={self.qty} | price={self.price:,.0f}{pnl_str} | {self.reason}"
        )


class SimPosition:
    def __init__(self, code: str, name: str, buy_price: float, quantity: int, buy_time: pd.Timestamp, buy_session: str):
        self.code = code
        self.name = name
        self.buy_price = buy_price
        self.quantity = quantity
        self.buy_time = buy_time
        self.buy_session = buy_session
        self.highest_price = buy_price


class Simulator:
    def __init__(self, initial_capital: float):
        self.initial_capital = initial_capital
        self.cash = initial_capital
        self.positions: dict[str, SimPosition] = {}
        self.trade_log: list[TradeRecord] = []
        self.cooldown_until: dict[str, pd.Timestamp] = {}
        self.completed_codes: set[str] = set()

    def in_cooldown(self, code: str, now: pd.Timestamp) -> bool:
        until = self.cooldown_until.get(code)
        return until is not None and now < until

    def set_cooldown(self, code: str, now: pd.Timestamp) -> None:
        self.cooldown_until[code] = now + pd.Timedelta(minutes=TRADE_COOLDOWN_MINUTES)

    def buy(self, code: str, name: str, price: float, now: pd.Timestamp, session: str, reason: str) -> bool:
        if self.in_cooldown(code, now) or price <= 0 or code in self.positions:
            return False
        if (not ALLOW_REBUY_SAME_CODE) and (not SIM_ALLOW_REENTRY_AFTER_COMPLETED_SELL) and code in self.completed_codes:
            return False

        qty = int(MAX_ORDER_AMOUNT_KRW / price)
        if qty <= 0:
            return False

        affordable_qty = int(self.cash / price)
        qty = min(qty, affordable_qty)
        if qty <= 0:
            return False

        self.cash -= price * qty
        self.positions[code] = SimPosition(code, name, price, qty, now, session)
        self.set_cooldown(code, now)

        rec = TradeRecord(code, name, "BUY", now, price, qty, reason, session)
        self.trade_log.append(rec)
        log(f"  {rec}")
        return True

    def sell(self, code: str, price: float, now: pd.Timestamp, reason: str, session: str) -> bool:
        pos = self.positions.get(code)
        if pos is None or pos.quantity <= 0 or price <= 0:
            return False

        proceeds = price * pos.quantity
        self.cash += proceeds

        rec = TradeRecord(code, pos.name, "SELL", now, price, pos.quantity, reason, session)
        rec.pnl_pct = (price / pos.buy_price - 1.0) * 100.0
        rec.pnl_krw = (price - pos.buy_price) * pos.quantity
        self.trade_log.append(rec)
        log(f"  {rec}")

        del self.positions[code]
        self.completed_codes.add(code)
        self.set_cooldown(code, now)
        return True

    def portfolio_value(self, last_prices: dict[str, float]) -> float:
        total = self.cash
        for code, pos in self.positions.items():
            total += last_prices.get(code, pos.buy_price) * pos.quantity
        return total


def get_latest_price_up_to(frame: pd.DataFrame, ts: pd.Timestamp) -> float | None:
    available = frame[frame.index <= ts]
    if available.empty:
        return None
    return float(available.iloc[-1]["close"])


def _format_pending_pnl(reason_prefix: str, pnl_pct: float) -> str:
    return f"{reason_prefix}_{pnl_pct * 100:.2f}%"


def _session_exit_plan(reason_prefix: str, pnl_pct: float) -> tuple[str, str]:
    if pnl_pct > 0:
        return "sell", _format_pending_pnl(f"{reason_prefix}_PROFIT_CLOSE", pnl_pct)
    if pnl_pct >= STOP_LOSS_PERCENT:
        return "hold", _format_pending_pnl(f"{reason_prefix}_OVERNIGHT_HOLD_WITHIN_STOP", pnl_pct)
    return "sell", _format_pending_pnl(f"{reason_prefix}_STOP_LOSS_BREACH", pnl_pct)


def run_scheduled_liquidations(
    sim: Simulator,
    price_frames: dict[str, pd.DataFrame],
    names: dict[str, str],
    ts: pd.Timestamp,
    state: dict,
    nxt_tradeable_fn,
) -> None:
    current_date = ts.date()
    if state.get("date") != current_date:
        state["date"] = current_date
        state["done_regular"] = False
        state["done_nxt"] = False

    if not state["done_regular"] and ts.time() >= REGULAR_FORCE_EXIT:
        state["done_regular"] = True
        for code in list(sim.positions.keys()):
            pos = sim.positions.get(code)
            if pos is None:
                continue
            price = get_latest_price_up_to(price_frames[code], ts)
            if price is None:
                continue
            pnl_pct = (price / pos.buy_price) - 1.0 if pos.buy_price > 0 else 0.0
            action, reason = _session_exit_plan("REGULAR_CLOSE", pnl_pct)
            if action == "sell":
                sim.sell(code, price, ts, reason, "regular")

    if ENABLE_NXT_SESSION and (not state["done_nxt"]) and ts.time() >= AFTERNOON_NXT_FORCE_EXIT:
        state["done_nxt"] = True
        for code in list(sim.positions.keys()):
            pos = sim.positions.get(code)
            if pos is None:
                continue
            if not bool(nxt_tradeable_fn(code)):
                continue
            price = get_latest_price_up_to(price_frames[code], ts)
            if price is None:
                continue
            pnl_pct = (price / pos.buy_price) - 1.0 if pos.buy_price > 0 else 0.0
            action, reason = _session_exit_plan("NXT_CLOSE", pnl_pct)
            if action == "sell":
                sim.sell(code, price, ts, reason, "afternoon_nxt")


def _load_nxt_flags(data_dir: Path) -> dict[str, bool]:
    """r001_data_collect_symbols_daily.py가 저장한 nxt_flags.json을 로드한다.

    당일분은 dict 형태로 읽어오며, 없으면 fallback 로직을 사용한다.
    """
    path = data_dir / "nxt_flags.json"
    if not path.exists():
        return {}
    try:
        with open(path, encoding="utf-8") as f:
            raw = json.load(f)
        return {str(code).zfill(6): bool(flag) for code, flag in raw.items()}
    except Exception as exc:
        log(f"WARNING: failed to load nxt_flags.json: {exc}")
        return {}



def simulate_date(
    date_str: str,
    data_root: Path,
    codes: list[str] | None = None,
    today_watch_codes: set[str] | None = None,
    names: dict[str, str] | None = None,
    initial_capital: float = SIM_INITIAL_CAPITAL,
    run_index: int | None = None,
    allow_all_txt_fallback: bool = False,
) -> int:
    global LAST_SIM_STATS, CURRENT_SIM_TS
    data_dir = data_root / date_str
    log(f"\n{'=' * 60}")
    log(f"Simulation date : {date_str} [R76 Live Price/BB Cross Simulation]")
    log(f"Data directory  : {data_dir}")
    log(f"Initial capital : {initial_capital:,.0f} KRW")
    if ENABLE_NXT_SESSION:
        log("MODE BANNER: REGULAR+NXT_MODE")
        log("Entry window    : 09:00-15:20 (정규) / NXT 세션 가능")
        log("Force exit      : 15:20 / 19:59 (당일 물량청산)")
    else:
        log("MODE BANNER: REGULAR_ONLY_MODE")
        log("Entry window    : 09:00-15:20 (정규장 전용)")
        log("Force exit      : 15:20 (당일 물량청산)")
    log(f"TP / SL / Trail : +{TAKE_PROFIT_PERCENT*100:.1f}% / {STOP_LOSS_PERCENT*100:.1f}% / -{TRAILING_STOP_FROM_PEAK*100:.1f}%(from peak)")
    log(f"{'=' * 60}\n")

    if not data_dir.exists():
        log(f"ERROR: Data directory not found: {data_dir}")
        return 1

    csv_files: dict[str, Path] = {}
    for path in sorted(data_dir.glob("*.txt")):
        code = _extract_code_from_stem(path.stem)
        if code is None:
            continue
        existing = csv_files.get(code)
        if existing is None:
            csv_files[code] = path
            continue

        def _is_preferred(candidate: Path, current: Path) -> bool:
            c_stem = candidate.stem.lower()
            cur_stem = current.stem.lower()
            c_rank = 0 if c_stem.endswith("_1m") else (2 if c_stem.endswith("_20s") else 1)
            cur_rank = 0 if cur_stem.endswith("_1m") else (2 if cur_stem.endswith("_20s") else 1)
            return c_rank < cur_rank

        if _is_preferred(path, existing):
            csv_files[code] = path
    if not csv_files:
        log(f"ERROR: No CSV files found in {data_dir}")
        return 1

    selected_names = dict(names or {})
    picks_file = resolve_picks_file(data_dir, date_str)
    picks = None if codes else load_picks(picks_file)
    watchlist_source = ""
    if codes:
        target_codes = {code.zfill(6) for code in codes}
        csv_files = {code: path for code, path in csv_files.items() if code in target_codes}
        watchlist_source = "--codes"
        log(f"Filtered by --codes: {sorted(target_codes)}")
    elif picks:
        csv_files = {code: path for code, path in csv_files.items() if code in picks}
        selected_names.update({code: name for code, name in picks.items() if code not in selected_names})
        watchlist_source = str(picks_file)
        log(f"Loaded {picks_file.name} ({len(picks)}): {sorted(picks.keys())}")
    elif today_watch_codes:
        csv_files = {code: path for code, path in csv_files.items() if code in today_watch_codes}
        watchlist_source = TODAY_CODE_FILE.name
        log(f"Loaded r76_trade_watchlist_today.txt ({len(today_watch_codes)}): {sorted(today_watch_codes)}")
    else:
        if not allow_all_txt_fallback:
            log(
                f"ERROR: watchlist file not found. expected one of: "
                f"{data_dir / ('_' + date_str + '_picks.txt')}, "
                f"{data_dir / (date_str + '_picks.txt')}, "
                f"{data_dir / PICKS_FILENAME}"
            )
            log("Hint: run r001 collector first to generate date-scoped picks files from r009 universe list.")
            return 1
        watchlist_source = f"{data_dir}/*.txt"
        log("WARNING: picks not found; --allow-all-txt-fallback enabled, using all TXT files in date folder")

    if not csv_files:
        log("ERROR: No matching TXT files after filtering")
        return 1

    frames: dict[str, pd.DataFrame] = {}
    price_frames: dict[str, pd.DataFrame] = {}
    target_date = datetime.strptime(date_str, "%Y%m%d").date()
    for code in sorted(csv_files):
        # price_frames: _20s 파일 우선 사용 (r006 실시간 가격 폴링과 동일한 세밀도)
        price_file = _find_code_txt_path_finest(data_dir, code) or csv_files[code]
        raw_df = read_ohlc_csv(price_file)
        if raw_df is None or raw_df.empty:
            log(f"Skipped {code}: failed to read intraday data")
            continue

        raw_df = raw_df[raw_df.index.date == target_date]
        if raw_df.empty:
            log(f"Skipped {code}: no bars on target date")
            continue

        strategy_df = normalize_to_strategy_bars(raw_df)
        if strategy_df is None or strategy_df.empty:
            log(f"Skipped {code}: failed to build strategy bars")
            continue

        frame = calculate_indicators(strategy_df)
        if frame is None or frame.empty:
            log(f"Skipped {code}: failed to build simulation frame")
            continue
        frames[code] = frame
        price_frames[code] = raw_df

    if not frames:
        log("ERROR: No valid chart data loaded")
        return 1

    log(f"Watchlist source: {watchlist_source}")

    # nxt_flags.json (data_collector가 생성한 파일 우선 사용, 없으면 fallback)
    nxt_flags_from_file = _load_nxt_flags(data_dir)
    if nxt_flags_from_file:
        log(f"Loaded nxt_flags.json ({len(nxt_flags_from_file)} codes) from {data_dir}")
    else:
        log(f"WARNING: nxt_flags.json not found in {data_dir}, falling back to NXT_ELIGIBLE_CODES_FALLBACK")

    def _is_nxt_tradeable(code: str) -> bool:
        if code in nxt_flags_from_file:
            return nxt_flags_from_file[code]
        return code in NXT_ELIGIBLE_CODES_FALLBACK

    for code in sorted(frames.keys()):
        log(f"WATCH | {code} | {selected_names.get(code, code)} | NXT={_is_nxt_tradeable(code)}")

    # 원시 데이터 타임스탬프를 이벤트 루프로 사용한다.
    # r006은 10초마다 실시간 API에서 새 가격을 가져오지만,
    # r007 시뮬 데이터는 20초(또는 1분) 간격 저장본이므로
    # 실제 새 가격이 존재하는 타임스탬프에서만 체크하는 것이 올바르다.
    # 합성 10초 그리드를 쓰면 동일 가격이 두 번 평가되어 cross_state 확인이
    # 실전보다 빠르게 발화하는 문제가 생긴다.
    all_times = sorted({ts for df in price_frames.values() for ts in df.index if ts.date() == target_date})
    if not all_times:
        log("ERROR: No intraday ticks found for target date")
        return 1

    data_interval_seconds = None
    if len(all_times) >= 2:
        diffs = pd.Series(all_times).diff().dropna().dt.total_seconds()
        data_interval_seconds = int(diffs.median())
    log(f"Sim tick interval: {data_interval_seconds}s (raw data cadence) — matches r006 {SIM_CHECK_INTERVAL_SECONDS}s live poll semantics")

    sim = Simulator(initial_capital=initial_capital)
    compare_basic = PaperStrategyTracker(name="BASIC_CROSS", mode="basic")
    compare_multi = PaperStrategyTracker(name="MULTI_FILTER", mode="multi")
    liq_state: dict[str, object] = {}
    signal_buy_bar: dict[str, pd.Timestamp] = {}
    signal_sell_bar: dict[str, pd.Timestamp] = {}
    post_buy_bb_drop_state: dict[str, dict] = {}
    breakeven_fail_state: dict[str, dict] = {}
    no_trend_exit_state: dict[str, dict] = {}
    sim_live_cross_state: dict[str, dict] = {}   # tracks live-price/BB-middle cross state per symbol

    for ts in all_times:
        CURRENT_SIM_TS = ts
        run_scheduled_liquidations(sim, price_frames, selected_names, ts, liq_state, _is_nxt_tradeable)
        latest_price_map: dict[str, float] = {}

        if is_regular_call_auction(ts):
            continue

        for code, frame in frames.items():
            nxt_tradeable = _is_nxt_tradeable(code)
            if not can_trade_code_now(ts, nxt_tradeable):
                continue

            raw_frame = price_frames.get(code)
            if raw_frame is None or raw_frame.empty:
                continue

            live_price = get_latest_price_up_to(raw_frame, ts)
            if live_price is None:
                continue

            latest_price_map[code] = live_price

            available = frame[frame.index <= ts]
            if len(available) < MIN_BARS_REQUIRED:
                continue

            cur = available.iloc[-1]
            price = float(live_price)
            session = classify_buy_session(ts)
            # 실전 매매와 동일한 cross signal tracker/confirm logic 적용
            _cur_bb_mid = _num(cur, "BB_MIDDLE")
            cross_info: dict[str, object] = (
                _update_sim_cross_state(sim_live_cross_state, code, ts, price, _cur_bb_mid)
                if not pd.isna(_cur_bb_mid)
                else {"signal": None, "relation": "on", "upper_trigger": 0.0, "lower_trigger": 0.0}
            )
            pos = sim.positions.get(code)

            if pos is None:
                post_buy_bb_drop_state.pop(code, None)
                breakeven_fail_state.pop(code, None)
                no_trend_exit_state.pop(code, None)

            entry_allowed = is_new_entry_allowed(ts, nxt_tradeable)
            if entry_allowed and is_startup_warmup_active(ts, nxt_tradeable):
                entry_allowed = False
            compare_basic.on_bar(code, available, ts, entry_allowed=entry_allowed)
            compare_multi.on_bar(code, available, ts, entry_allowed=entry_allowed, live_price=price)

            log_detail(
                f"  [CHECK] {code}({selected_names.get(code, code)}) | {ts:%H:%M:%S} | bars={len(available)} price={price:,.0f} | "
                f"MA5={_num(cur, 'MA_5'):.1f} BB_MID={_num(cur, 'BB_MIDDLE'):.1f} BB_UP={_num(cur, 'BB_UPPER'):.1f} BB_LW={_num(cur, 'BB_LOWER'):.1f} | "
                f"RSI={_num(cur, 'RSI'):.1f} SIG={_num(cur, 'RSI_SIGNAL'):.1f} | "
                f"K={_num(cur, 'STOCH_K'):.1f} D={_num(cur, 'STOCH_D'):.1f} | "
                f"WR={_num(cur, 'WILLIAMS_R'):.1f} WD={_num(cur, 'WILLIAMS_D'):.1f} | "
                f"MACD={_num(cur, 'MACD'):.2f} SIG={_num(cur, 'MACD_SIGNAL'):.2f} HIST={_num(cur, 'MACD_HIST'):.2f} | "
                f"ADX={_num(cur, 'ADX'):.1f} +DI={_num(cur, 'DI_PLUS'):.1f} -DI={_num(cur, 'DI_MINUS'):.1f} | "
                f"VOL={_num(cur, 'volume'):,.0f} VOLMA={_num(cur, 'VOL_MA20'):,.0f} | "
                f"VWAP={_num(cur, 'VWAP'):,.0f} OBV={_num(cur, 'OBV'):,.0f} OBVMA={_num(cur, 'OBV_MA'):,.0f}"
            )

            if pos is not None:
                profit_pct = price / pos.buy_price - 1.0
                pos.highest_price = max(pos.highest_price, price)
                peak_pnl_pct = (pos.highest_price / pos.buy_price) - 1.0 if pos.highest_price > 0 and pos.buy_price > 0 else 0.0
                giveback = peak_pnl_pct - profit_pct
                if profit_pct >= TAKE_PROFIT_PERCENT and not ENABLE_TP_EXTENSION_TRAILING:
                    sim.sell(code, price, ts, f"TAKE_PROFIT_+{TAKE_PROFIT_PERCENT*100:.1f}%", session)
                    signal_sell_bar[code] = ts
                    log(f"  [SELL EXECUTED] {code} | TAKE_PROFIT_+{TAKE_PROFIT_PERCENT*100:.1f}% | price={price:,.0f}")
                    continue
                # ── POST-BUY ENTRY DROP GUARD ─────────────────────────────────────
                _held_for_guard = (ts - pos.buy_time).total_seconds()
                if _held_for_guard <= POST_BUY_BB_DROP_ARMED_SECONDS:
                    _drop_hold_seconds = update_timed_condition_state(
                        post_buy_bb_drop_state,
                        code,
                        pos.buy_time,
                        ts,
                        price < pos.buy_price * (1.0 - POST_BUY_BB_DROP_PCT),
                    )
                    if _drop_hold_seconds >= POST_BUY_DROP_CONFIRM_SECONDS:
                        _drop_pct_guard = (price / pos.buy_price - 1.0) * 100.0
                        reason_bbdrop = f"POST_BUY_ENTRY_DROP_{POST_BUY_BB_DROP_PCT*100:.1f}pct_{POST_BUY_DROP_CONFIRM_SECONDS:.0f}s"
                        log(
                            f"  [SELL TRIGGER] {code} | {reason_bbdrop} | "
                            f"held={_held_for_guard:.0f}s price={price:,.0f} entry={pos.buy_price:,.0f} "
                            f"drop={_drop_pct_guard:.2f}% hold={_drop_hold_seconds:.0f}s pnl={profit_pct*100:.2f}%"
                        )
                        post_buy_bb_drop_state.pop(code, None)
                        breakeven_fail_state.pop(code, None)
                        no_trend_exit_state.pop(code, None)
                        sim.sell(code, price, ts, reason_bbdrop, session)
                        signal_sell_bar[code] = ts
                        log(f"  [SELL EXECUTED] {code} | {reason_bbdrop} | price={price:,.0f}")
                        continue
                else:
                    post_buy_bb_drop_state.pop(code, None)
                # ── END POST-BUY ENTRY DROP GUARD ─────────────────────────────────

                # ── BREAKEVEN FAILURE GUARD ────────────────────────────────────────
                _breakeven_hold_seconds = update_timed_condition_state(
                    breakeven_fail_state,
                    code,
                    pos.buy_time,
                    ts,
                    peak_pnl_pct >= BREAKEVEN_FAIL_ARM_PNL
                    and profit_pct < 0
                    and giveback >= BREAKEVEN_FAIL_GIVEBACK_PCT,
                )
                if _breakeven_hold_seconds >= BREAKEVEN_FAIL_CONFIRM_SECONDS:
                    reason_breakeven = (
                        f"BREAKEVEN_FAIL_peak{BREAKEVEN_FAIL_ARM_PNL*100:.1f}_"
                        f"giveback{BREAKEVEN_FAIL_GIVEBACK_PCT*100:.2f}_{BREAKEVEN_FAIL_CONFIRM_SECONDS:.0f}s"
                    )
                    log(
                        f"  [SELL TRIGGER] {code} | {reason_breakeven} | held={_held_for_guard:.0f}s "
                        f"price={price:,.0f} entry={pos.buy_price:,.0f} peak={pos.highest_price:,.0f} "
                        f"peak_pnl={peak_pnl_pct*100:.2f}% giveback={giveback*100:.2f}%"
                    )
                    post_buy_bb_drop_state.pop(code, None)
                    breakeven_fail_state.pop(code, None)
                    no_trend_exit_state.pop(code, None)
                    sim.sell(code, price, ts, reason_breakeven, session)
                    signal_sell_bar[code] = ts
                    log(f"  [SELL EXECUTED] {code} | {reason_breakeven} | price={price:,.0f}")
                    continue
                # ── END BREAKEVEN FAILURE GUARD ───────────────────────────────────

                # ── NO-TREND TIME EXIT ────────────────────────────────────────────
                _bb_mid_guard = _num(cur, "BB_MIDDLE")
                _no_trend_condition = (
                    _held_for_guard >= NO_TREND_EXIT_ARM_SECONDS
                    and peak_pnl_pct <= NO_TREND_EXIT_MAX_PEAK_PNL
                    and profit_pct <= NO_TREND_EXIT_MIN_PNL
                    and _bb_mid_guard > 0
                    and price < _bb_mid_guard
                )
                _no_trend_hold_seconds = update_timed_condition_state(
                    no_trend_exit_state,
                    code,
                    pos.buy_time,
                    ts,
                    _no_trend_condition,
                )
                if _no_trend_hold_seconds >= NO_TREND_EXIT_CONFIRM_SECONDS:
                    reason_no_trend = (
                        f"NO_TREND_EXIT_{NO_TREND_EXIT_ARM_SECONDS/60:.0f}m_"
                        f"peakLT{NO_TREND_EXIT_MAX_PEAK_PNL*100:.1f}_{NO_TREND_EXIT_CONFIRM_SECONDS:.0f}s"
                    )
                    log(
                        f"  [SELL TRIGGER] {code} | {reason_no_trend} | held={_held_for_guard:.0f}s "
                        f"price={price:,.0f} bb_mid={_bb_mid_guard:,.1f} pnl={profit_pct*100:.2f}% "
                        f"peak_pnl={peak_pnl_pct*100:.2f}% hold={_no_trend_hold_seconds:.0f}s"
                    )
                    post_buy_bb_drop_state.pop(code, None)
                    breakeven_fail_state.pop(code, None)
                    no_trend_exit_state.pop(code, None)
                    sim.sell(code, price, ts, reason_no_trend, session)
                    signal_sell_bar[code] = ts
                    log(f"  [SELL EXECUTED] {code} | {reason_no_trend} | price={price:,.0f}")
                    continue
                # ── END NO-TREND TIME EXIT ────────────────────────────────────────

                _held_sl = (ts - pos.buy_time).total_seconds()
                _sl_threshold = STOP_LOSS_EARLY_PERCENT if _held_sl < STOP_LOSS_MIN_HOLD_SECONDS else STOP_LOSS_PERCENT
                if profit_pct <= _sl_threshold:
                    _sl_label = f"STOP_LOSS_EARLY_{_sl_threshold*100:.1f}%" if _held_sl < STOP_LOSS_MIN_HOLD_SECONDS else f"STOP_LOSS_{_sl_threshold*100:.1f}%"
                    sim.sell(code, price, ts, _sl_label, session)
                    signal_sell_bar[code] = ts
                    log(f"  [SELL EXECUTED] {code} | {_sl_label} | held={_held_sl:.0f}s price={price:,.0f}")
                    continue
                highest_price = float(pos.highest_price)
                if highest_price > 0 and pos.buy_price > 0:
                    current_pnl_pct = profit_pct
                    giveback = peak_pnl_pct - current_pnl_pct
                    if ENABLE_TP_EXTENSION_TRAILING and peak_pnl_pct >= TAKE_PROFIT_PERCENT:
                        trail_threshold = TP_EXTENSION_TRAIL_FROM_PEAK
                        reason_ts = f"TP_EXTENSION_TRAIL_{TP_EXTENSION_TRAIL_FROM_PEAK*100:.1f}%"
                    else:
                        trail_threshold = TRAILING_STOP_FROM_PEAK
                        reason_ts = f"TRAILING_STOP_GIVEBACK_{TRAILING_STOP_FROM_PEAK*100:.1f}%"
                    if peak_pnl_pct > 0 and current_pnl_pct > 0 and giveback >= trail_threshold:
                        sim.sell(code, price, ts, reason_ts, session)
                        signal_sell_bar[code] = ts
                        log(f"  [SELL EXECUTED] {code} | {reason_ts} | price={price:,.0f}")
                        continue

                if signal_sell_bar.get(code) == ts:
                    continue

                should_sell, reason = check_sell_condition_r76_sim(available, profit_pct, price, cross_info)
                if should_sell:
                    sim.sell(code, price, ts, reason, session)
                    signal_sell_bar[code] = ts
                    log(f"  [SELL EVAL] {code} | OK {reason} | pnl={profit_pct*100:.2f}%")
                elif (
                    reason.startswith("AUX_BLOCKED")
                    or reason.startswith("LIVE_PRICE_BB_DOWN_CROSS_BLOCKED")
                    or reason.startswith("LIVE_PRICE_BB_DOWN_CROSS_WEAK")
                    or reason.startswith("BOX_RANGE_HOLD")
                ):
                    log_detail(f"  [SELL HOLD] {code} | {reason}")
                continue

            if not is_new_entry_allowed(ts, nxt_tradeable):
                continue
            if is_startup_warmup_active(ts, nxt_tradeable):
                continue
            if sim.in_cooldown(code, ts):
                continue
            if (not ALLOW_REBUY_SAME_CODE) and code in sim.completed_codes:
                continue
            if signal_buy_bar.get(code) == ts:
                continue

            should_buy, reason = check_buy_condition_r76_sim(available, ts, price, cross_info)

            if should_buy:
                log(
                    f"  [BUY SIGNAL] {code} | {ts:%H:%M} | {reason} | "
                    f"MA5={_num(cur,'MA_5'):.1f} BB_MID={_num(cur,'BB_MIDDLE'):.1f} | "
                    f"RSI={_num(cur,'RSI'):.1f} SIG={_num(cur,'RSI_SIGNAL'):.1f} | "
                    f"K={_num(cur,'STOCH_K'):.1f} D={_num(cur,'STOCH_D'):.1f} | "
                    f"WR={_num(cur,'WILLIAMS_R'):.1f} WD={_num(cur,'WILLIAMS_D'):.1f}"
                )
                if sim.buy(code, selected_names.get(code, code), price, ts, session, reason):
                    signal_buy_bar[code] = ts
                    log(f"  [BUY EVAL] {code} | OK {reason} | price={price:,.0f}")
                else:
                    log_detail(f"  [BUY REJECT] {code} | ORDER_REJECTED")
            else:
                log_detail(f"  [BUY REJECT] {code} | {reason}")



        if ts.time() >= REGULAR_FORCE_EXIT:
            compare_basic.force_close_all(latest_price_map, "EOD_FLAT_1520_ALL")
            compare_multi.force_close_all(latest_price_map, "EOD_FLAT_1520_ALL")

        if ENABLE_NXT_SESSION and ts.time() >= AFTERNOON_NXT_FORCE_EXIT:
            compare_basic.force_close_all(latest_price_map, "EOD_FLAT_1959_ALL")
            compare_multi.force_close_all(latest_price_map, "EOD_FLAT_1959_ALL")

    final_end_time = AFTERNOON_NXT_END if ENABLE_NXT_SESSION else REGULAR_END
    final_close_time = pd.Timestamp(datetime.combine(target_date, final_end_time))
    CURRENT_SIM_TS = final_close_time
    for code in list(sim.positions.keys()):
        price = get_latest_price_up_to(price_frames[code], final_close_time)
        if price is None:
            continue
        session = sim.positions[code].buy_session
        sim.sell(code, price, final_close_time, "EOD_CLOSE", session)

    CURRENT_SIM_TS = None

    last_prices = {
        code: float(frame[frame.index.date == target_date].iloc[-1]["close"])
        for code, frame in price_frames.items()
        if not frame[frame.index.date == target_date].empty
    }
    final_value = sim.portfolio_value(last_prices)
    total_pnl = final_value - initial_capital
    total_pnl_pct = total_pnl / initial_capital * 100.0 if initial_capital else 0.0

    sell_trades = [record for record in sim.trade_log if record.action == "SELL" and record.pnl_krw is not None]
    realized_pnl = sum(record.pnl_krw for record in sell_trades)
    wins = [record for record in sell_trades if record.pnl_krw > 0]
    losses = [record for record in sell_trades if record.pnl_krw <= 0]


    traded_codes: list[str] = []
    seen: set[str] = set()
    for record in sim.trade_log:
        if record.code not in seen:
            traded_codes.append(record.code)
            seen.add(record.code)

    log(f"\n{'=' * 60}")
    log(f"SIMULATION RESULTS [{date_str}] - R76 MA5-BB Cross")
    log(f"{'=' * 60}")

    for code in traded_codes:
        name = selected_names.get(code) or SAMPLE_CODE_MAP.get(code) or code
        buys = [record for record in sim.trade_log if record.code == code and record.action == "BUY"]
        sells = [record for record in sim.trade_log if record.code == code and record.action == "SELL"]
        code_pnl = sum(record.pnl_krw or 0.0 for record in sells)

        # Show both code and name in the header line, e.g. [009830] 한화솔루션
        raw(f"\n  [{code}] {name}")
        raw(f"  {'-' * 50}")
        for record in buys:
            bar_dt = record.bar_time.strftime("%Y-%m-%d %H:%M")
            raw(f"    {bar_dt}  매수  qty={record.qty:>4d}  price={record.price:>9,.0f}  [{record.reason}]")
        for record in sells:
            pnl_pct = record.pnl_pct if record.pnl_pct is not None else 0.0
            pnl_krw = record.pnl_krw if record.pnl_krw is not None else 0.0
            bar_dt = record.bar_time.strftime("%Y-%m-%d %H:%M")
            raw(
                f"    {bar_dt}  매도  qty={record.qty:>4d}  price={record.price:>9,.0f}"
                f"  {pnl_pct:+.2f}%  {pnl_krw:+,.0f} KRW  [{record.reason}]"
            )
        raw(f"    {'-' * 46}")
        raw(f"    종목 손익: {code_pnl:+,.0f} KRW  (매수 {len(buys)}건 / 매도 {len(sells)}건)")

    total_sell_count = len(sell_trades)
    win_rate = len(wins) / total_sell_count * 100.0 if total_sell_count else 0.0
    compare_basic.force_close_all(last_prices, "SESSION_END_FORCE")
    compare_multi.force_close_all(last_prices, "SESSION_END_FORCE")
    basic_stats = compare_basic.summary_dict()
    multi_stats = compare_multi.summary_dict()

    raw(f"\n{'=' * 60}")
    raw("전체 결과 (R76 MA5-BB Cross)")
    raw(f"{'-' * 60}")
    raw(f"  초기 자본    : {initial_capital:>15,.0f} KRW")
    raw(f"  최종 자산    : {final_value:>15,.0f} KRW")
    raw(f"  실현 손익    : {realized_pnl:>+15,.0f} KRW")
    raw(f"  총 손익      : {total_pnl:>+15,.0f} KRW  ({total_pnl_pct:+.2f}%)")
    raw(f"  잔여 현금    : {sim.cash:>15,.0f} KRW")
    raw(f"{'-' * 60}")
    raw(f"  매도 건수    : {total_sell_count}건 (익절 {len(wins)}건/ 손절·기타 {len(losses)}건)")
    raw(f"  승률         : {win_rate:.1f}%")
    raw(f"{'=' * 60}\n")

    raw(f"{'=' * 60}")
    raw("전략 비교 결과 (기본전략 vs 멀티필터)")
    raw(f"{'-' * 60}")
    raw(
        f"  BASIC_CROSS  : trades={basic_stats['trades']} wins={basic_stats['wins']} losses={basic_stats['losses']} "
        f"win_rate={basic_stats['win_rate']:.1f}% avg_pnl={basic_stats['avg_pnl_pct']:.2f}% "
        f"total_pnl={basic_stats['total_pnl_pct']:.2f}% equity={basic_stats['equity']:.4f}"
    )
    raw(
        f"  MULTI_FILTER : trades={multi_stats['trades']} wins={multi_stats['wins']} losses={multi_stats['losses']} "
        f"win_rate={multi_stats['win_rate']:.1f}% avg_pnl={multi_stats['avg_pnl_pct']:.2f}% "
        f"total_pnl={multi_stats['total_pnl_pct']:.2f}% equity={multi_stats['equity']:.4f}"
    )
    raw(f"{'=' * 60}\n")

    LAST_SIM_STATS = {
        "date": date_str,
        "initial_capital": float(initial_capital),
        "final_value": float(final_value),
        "realized_pnl": float(realized_pnl),
        "total_pnl": float(total_pnl),
        "total_pnl_pct": float(total_pnl_pct),
        "sell_count": int(total_sell_count),
        "win_count": int(len(wins)),
        "loss_count": int(len(losses)),
        "win_rate": float(win_rate),
        "traded_code_count": int(len(traded_codes)),
        "compare_basic_trades": int(basic_stats["trades"]),
        "compare_basic_total_pnl_pct": float(basic_stats["total_pnl_pct"]),
        "compare_multi_trades": int(multi_stats["trades"]),
        "compare_multi_total_pnl_pct": float(multi_stats["total_pnl_pct"]),
    }

    append_daily_result_csv(
        {
            "date": date_str,
            "initial_capital": float(initial_capital),
            "final_value": float(final_value),
            "realized_pnl": float(realized_pnl),
            "total_pnl": float(total_pnl),
            "total_pnl_pct": float(total_pnl_pct),
            "sell_count": int(total_sell_count),
            "win_count": int(len(wins)),
            "loss_count": int(len(losses)),
            "win_rate": float(win_rate),
            "traded_code_count": int(len(traded_codes)),
        }
    )

    run_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    append_compare_result_csv(
        date_str,
        "BASIC_CROSS",
        {
            "run_at": run_at,
            "date": date_str,
            "strategy": "BASIC_CROSS",
            "trades": int(basic_stats["trades"]),
            "wins": int(basic_stats["wins"]),
            "losses": int(basic_stats["losses"]),
            "win_rate": float(basic_stats["win_rate"]),
            "avg_pnl_pct": float(basic_stats["avg_pnl_pct"]),
            "total_pnl_pct": float(basic_stats["total_pnl_pct"]),
            "equity": float(basic_stats["equity"]),
            "fee_buy_rate": COMPARE_FEE_BUY_RATE,
            "fee_sell_rate": COMPARE_FEE_SELL_RATE,
            "slippage_rate": COMPARE_SLIPPAGE_RATE,
        },
    )
    append_compare_result_csv(
        date_str,
        "MULTI_FILTER",
        {
            "run_at": run_at,
            "date": date_str,
            "strategy": "MULTI_FILTER",
            "trades": int(multi_stats["trades"]),
            "wins": int(multi_stats["wins"]),
            "losses": int(multi_stats["losses"]),
            "win_rate": float(multi_stats["win_rate"]),
            "avg_pnl_pct": float(multi_stats["avg_pnl_pct"]),
            "total_pnl_pct": float(multi_stats["total_pnl_pct"]),
            "equity": float(multi_stats["equity"]),
            "fee_buy_rate": COMPARE_FEE_BUY_RATE,
            "fee_sell_rate": COMPARE_FEE_SELL_RATE,
            "slippage_rate": COMPARE_SLIPPAGE_RATE,
        },
    )

    # --- 시뮬레이션 결과 로그 파일 저장 ---
    try:
        # 로그 파일명: YYYYMMDD_simulate_001_result.txt, 002, ...
        out_dir = data_dir
        out_dir.mkdir(parents=True, exist_ok=True)
        idx = run_index if run_index is not None else _next_simulation_run_index(out_dir)
        out_path = out_dir / f"{date_str}_simulate_{idx:03d}_result.txt"
        with open(out_path, "w", encoding="utf-8-sig") as f:
            f.write("\n".join(_RAW_LOG_BUFFER))
        print(f"[INFO] Simulation log saved: {out_path}")
    except Exception as exc:
        print(f"[WARN] Failed to save simulation log: {exc}")
    return 0


import sys
import threading

# --- stdout/stderr tee 래퍼 ---
class Tee:
    def __init__(self, *files):
        self.files = files
        self.lock = threading.Lock()
    def write(self, data):
        with self.lock:
            for f in self.files:
                try:
                    f.write(data)
                except Exception:
                    pass
    def flush(self):
        with self.lock:
            for f in self.files:
                try:
                    f.flush()
                except Exception:
                    pass


def _next_simulation_run_index(day_dir: Path) -> int:
    """Find next shared run index for both result and full log outputs."""
    for idx in range(1, 1000):
        result_path = day_dir / f"{day_dir.name}_simulate_{idx:03d}_result.txt"
        full_log_path = day_dir / f"{day_dir.name}_simulate_{idx:03d}_full_log.txt"
        if not result_path.exists() and not full_log_path.exists():
            return idx
    return 999

def main() -> None:
    global TAKE_PROFIT_PERCENT, STOP_LOSS_PERCENT, TRAILING_STOP_FROM_PEAK
    global LOG_SUMMARY_MODE, COMPARE_FEE_BUY_RATE, COMPARE_FEE_SELL_RATE, COMPARE_SLIPPAGE_RATE

    parser = argparse.ArgumentParser(description="Simulate R76 strategy using date CSV/TXT data (1-minute input supported)")
    parser.add_argument("--date", required=True, help="Simulation date in YYYYMMDD format")
    parser.add_argument("--codes", nargs="*", help="Optional stock codes to simulate")
    parser.add_argument(
        "--data-root",
        default=str(SCRIPT_DIR / DATA_DIR_NAME),
        help="Root directory containing date subfolders",
    )
    parser.add_argument(
        "--capital",
        type=float,
        default=SIM_INITIAL_CAPITAL,
        help="Initial capital in KRW",
    )
    parser.add_argument(
        "--today-code-file",
        default=str(TODAY_CODE_FILE),
        help="Path to r76_trade_watchlist_today.txt for code names",
    )
    parser.add_argument(
        "--use-today-code-watchlist",
        action="store_true",
        help="Use r76_trade_watchlist_today.txt as watchlist when --codes and picks.txt are not provided",
    )
    parser.add_argument(
        "--symbols-file",
        default=str(SCRIPT_DIR / "r76_universe_symbols_master.csv"),
        help="Path to r76_universe_symbols_master.csv used by get_simulation_data.py",
    )
    parser.add_argument(
        "--tp",
        type=float,
        default=None,
        help="Take-profit ratio (e.g. 0.035 for 3.5%%)",
    )
    parser.add_argument(
        "--sl",
        type=float,
        default=None,
        help="Stop-loss ratio as positive number (e.g. 0.015 for 1.5%%)",
    )
    parser.add_argument(
        "--trail",
        type=float,
        default=None,
        help="Trailing stop from peak ratio (e.g. 0.012 for 1.2%%)",
    )
    parser.add_argument(
        "--summary",
        action="store_true",
        help="Reduce log volume by suppressing high-frequency per-bar hold/reject/check logs",
    )
    parser.add_argument(
        "--compare-fee-buy",
        type=float,
        default=COMPARE_FEE_BUY_RATE,
        help="Compare strategy buy fee rate (e.g. 0.00015)",
    )
    parser.add_argument(
        "--compare-fee-sell",
        type=float,
        default=COMPARE_FEE_SELL_RATE,
        help="Compare strategy sell fee rate (e.g. 0.00015)",
    )
    parser.add_argument(
        "--compare-slippage",
        type=float,
        default=COMPARE_SLIPPAGE_RATE,
        help="Compare strategy one-way slippage rate (e.g. 0.0002)",
    )
    args = parser.parse_args()


    try:
        datetime.strptime(args.date, "%Y%m%d")
    except ValueError:
        print(f"ERROR: Invalid date format: {args.date} (expected YYYYMMDD)")
        sys.exit(1)

    # --- 전체 실행 로그 파일 핸들러 및 tee 설정 ---
    # 로그 파일명: YYYYMMDD_simulate_001_full_log.txt, 002, ...
    log_dir = Path(args.data_root) / args.date
    log_dir.mkdir(parents=True, exist_ok=True)
    run_index = _next_simulation_run_index(log_dir)
    log_path = log_dir / f"{args.date}_simulate_{run_index:03d}_full_log.txt"
    # logging 파일 핸들러 추가
    file_handler = logging.FileHandler(log_path, encoding="utf-8")
    file_handler.setFormatter(logging.Formatter("[%(levelname)s] %(message)s"))
    logging.getLogger().addHandler(file_handler)
    # stdout/stderr tee
    orig_stdout, orig_stderr = sys.stdout, sys.stderr
    log_file = open(log_path, "a", encoding="utf-8")
    sys.stdout = Tee(orig_stdout, log_file)
    sys.stderr = Tee(orig_stderr, log_file)
    print(f"[INFO] Full simulation log will be saved to: {log_path}")

    if args.tp is not None:
        TAKE_PROFIT_PERCENT = float(args.tp)
    if args.sl is not None:
        STOP_LOSS_PERCENT = -abs(float(args.sl))
    if args.trail is not None:
        TRAILING_STOP_FROM_PEAK = abs(float(args.trail))

    LOG_SUMMARY_MODE = bool(args.summary)
    COMPARE_FEE_BUY_RATE = max(0.0, float(args.compare_fee_buy))
    COMPARE_FEE_SELL_RATE = max(0.0, float(args.compare_fee_sell))
    COMPARE_SLIPPAGE_RATE = max(0.0, float(args.compare_slippage))

    if LOG_SUMMARY_MODE:
        log("Summary log mode enabled: high-frequency check/hold/reject logs are suppressed")
    log(
        f"Compare cost model: fee_buy={COMPARE_FEE_BUY_RATE:.6f}, "
        f"fee_sell={COMPARE_FEE_SELL_RATE:.6f}, slippage={COMPARE_SLIPPAGE_RATE:.6f}"
    )

    names = load_symbols_name_map(Path(args.symbols_file))
    names_from_today = load_code_name_map(Path(args.today_code_file))
    for code, name in names_from_today.items():
        names.setdefault(code, name)
    if args.use_today_code_watchlist and names_from_today:
        today_watch_codes: set[str] | None = set(names_from_today.keys())
        log(
            f"Today-code watchlist enabled by option: {Path(args.today_code_file)} "
            f"({len(today_watch_codes)} codes)"
        )
    else:
        today_watch_codes = None
        if args.use_today_code_watchlist:
            log(f"WARNING: today-code watchlist enabled but file is empty or missing: {Path(args.today_code_file)}")
    exit_code = simulate_date(
        date_str=args.date,
        data_root=Path(args.data_root),
        codes=args.codes,
        today_watch_codes=today_watch_codes,
        names=names,
        initial_capital=args.capital,
        run_index=run_index,
    )
    # 핸들러/tee 정리
    try:
        sys.stdout.flush()
        sys.stderr.flush()
        log_file.flush()
        log_file.close()
        logging.getLogger().removeHandler(file_handler)
    except Exception:
        pass
    raise SystemExit(exit_code)


if __name__ == "__main__":
    main()
